// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/bug_service.proto

package pb

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BugSearchRequest struct {
	Values               map[string]string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Limit                int64             `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int64             `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Orderby              string            `protobuf:"bytes,4,opt,name=orderby,proto3" json:"orderby,omitempty"`
	Orderdesc            bool              `protobuf:"varint,5,opt,name=orderdesc,proto3" json:"orderdesc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BugSearchRequest) Reset()         { *m = BugSearchRequest{} }
func (m *BugSearchRequest) String() string { return proto.CompactTextString(m) }
func (*BugSearchRequest) ProtoMessage()    {}
func (*BugSearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_42e24d81e69473d1, []int{0}
}

func (m *BugSearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BugSearchRequest.Unmarshal(m, b)
}
func (m *BugSearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BugSearchRequest.Marshal(b, m, deterministic)
}
func (m *BugSearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BugSearchRequest.Merge(m, src)
}
func (m *BugSearchRequest) XXX_Size() int {
	return xxx_messageInfo_BugSearchRequest.Size(m)
}
func (m *BugSearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BugSearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BugSearchRequest proto.InternalMessageInfo

func (m *BugSearchRequest) GetValues() map[string]string {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *BugSearchRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *BugSearchRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *BugSearchRequest) GetOrderby() string {
	if m != nil {
		return m.Orderby
	}
	return ""
}

func (m *BugSearchRequest) GetOrderdesc() bool {
	if m != nil {
		return m.Orderdesc
	}
	return false
}

type BugSearchResponse struct {
	Bugs                 []*Bug   `protobuf:"bytes,1,rep,name=Bugs,proto3" json:"Bugs,omitempty"`
	Total                int64    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BugSearchResponse) Reset()         { *m = BugSearchResponse{} }
func (m *BugSearchResponse) String() string { return proto.CompactTextString(m) }
func (*BugSearchResponse) ProtoMessage()    {}
func (*BugSearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_42e24d81e69473d1, []int{1}
}

func (m *BugSearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BugSearchResponse.Unmarshal(m, b)
}
func (m *BugSearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BugSearchResponse.Marshal(b, m, deterministic)
}
func (m *BugSearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BugSearchResponse.Merge(m, src)
}
func (m *BugSearchResponse) XXX_Size() int {
	return xxx_messageInfo_BugSearchResponse.Size(m)
}
func (m *BugSearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BugSearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BugSearchResponse proto.InternalMessageInfo

func (m *BugSearchResponse) GetBugs() []*Bug {
	if m != nil {
		return m.Bugs
	}
	return nil
}

func (m *BugSearchResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type BugCreateRequest struct {
	Values               map[string]string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BugCreateRequest) Reset()         { *m = BugCreateRequest{} }
func (m *BugCreateRequest) String() string { return proto.CompactTextString(m) }
func (*BugCreateRequest) ProtoMessage()    {}
func (*BugCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_42e24d81e69473d1, []int{2}
}

func (m *BugCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BugCreateRequest.Unmarshal(m, b)
}
func (m *BugCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BugCreateRequest.Marshal(b, m, deterministic)
}
func (m *BugCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BugCreateRequest.Merge(m, src)
}
func (m *BugCreateRequest) XXX_Size() int {
	return xxx_messageInfo_BugCreateRequest.Size(m)
}
func (m *BugCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BugCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BugCreateRequest proto.InternalMessageInfo

func (m *BugCreateRequest) GetValues() map[string]string {
	if m != nil {
		return m.Values
	}
	return nil
}

type BugCreateResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BugCreateResponse) Reset()         { *m = BugCreateResponse{} }
func (m *BugCreateResponse) String() string { return proto.CompactTextString(m) }
func (*BugCreateResponse) ProtoMessage()    {}
func (*BugCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_42e24d81e69473d1, []int{3}
}

func (m *BugCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BugCreateResponse.Unmarshal(m, b)
}
func (m *BugCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BugCreateResponse.Marshal(b, m, deterministic)
}
func (m *BugCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BugCreateResponse.Merge(m, src)
}
func (m *BugCreateResponse) XXX_Size() int {
	return xxx_messageInfo_BugCreateResponse.Size(m)
}
func (m *BugCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BugCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BugCreateResponse proto.InternalMessageInfo

func (m *BugCreateResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type BugReadRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BugReadRequest) Reset()         { *m = BugReadRequest{} }
func (m *BugReadRequest) String() string { return proto.CompactTextString(m) }
func (*BugReadRequest) ProtoMessage()    {}
func (*BugReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_42e24d81e69473d1, []int{4}
}

func (m *BugReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BugReadRequest.Unmarshal(m, b)
}
func (m *BugReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BugReadRequest.Marshal(b, m, deterministic)
}
func (m *BugReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BugReadRequest.Merge(m, src)
}
func (m *BugReadRequest) XXX_Size() int {
	return xxx_messageInfo_BugReadRequest.Size(m)
}
func (m *BugReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BugReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BugReadRequest proto.InternalMessageInfo

func (m *BugReadRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type BugReadResponse struct {
	Bug                  *Bug     `protobuf:"bytes,1,opt,name=bug,proto3" json:"bug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BugReadResponse) Reset()         { *m = BugReadResponse{} }
func (m *BugReadResponse) String() string { return proto.CompactTextString(m) }
func (*BugReadResponse) ProtoMessage()    {}
func (*BugReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_42e24d81e69473d1, []int{5}
}

func (m *BugReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BugReadResponse.Unmarshal(m, b)
}
func (m *BugReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BugReadResponse.Marshal(b, m, deterministic)
}
func (m *BugReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BugReadResponse.Merge(m, src)
}
func (m *BugReadResponse) XXX_Size() int {
	return xxx_messageInfo_BugReadResponse.Size(m)
}
func (m *BugReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BugReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BugReadResponse proto.InternalMessageInfo

func (m *BugReadResponse) GetBug() *Bug {
	if m != nil {
		return m.Bug
	}
	return nil
}

type BugUpdateRequest struct {
	Id                   int64             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Values               map[string]string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BugUpdateRequest) Reset()         { *m = BugUpdateRequest{} }
func (m *BugUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*BugUpdateRequest) ProtoMessage()    {}
func (*BugUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_42e24d81e69473d1, []int{6}
}

func (m *BugUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BugUpdateRequest.Unmarshal(m, b)
}
func (m *BugUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BugUpdateRequest.Marshal(b, m, deterministic)
}
func (m *BugUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BugUpdateRequest.Merge(m, src)
}
func (m *BugUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_BugUpdateRequest.Size(m)
}
func (m *BugUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BugUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BugUpdateRequest proto.InternalMessageInfo

func (m *BugUpdateRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BugUpdateRequest) GetValues() map[string]string {
	if m != nil {
		return m.Values
	}
	return nil
}

type BugUpdateResponse struct {
	Rowsaffected         int64    `protobuf:"varint,1,opt,name=rowsaffected,proto3" json:"rowsaffected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BugUpdateResponse) Reset()         { *m = BugUpdateResponse{} }
func (m *BugUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*BugUpdateResponse) ProtoMessage()    {}
func (*BugUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_42e24d81e69473d1, []int{7}
}

func (m *BugUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BugUpdateResponse.Unmarshal(m, b)
}
func (m *BugUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BugUpdateResponse.Marshal(b, m, deterministic)
}
func (m *BugUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BugUpdateResponse.Merge(m, src)
}
func (m *BugUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_BugUpdateResponse.Size(m)
}
func (m *BugUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BugUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BugUpdateResponse proto.InternalMessageInfo

func (m *BugUpdateResponse) GetRowsaffected() int64 {
	if m != nil {
		return m.Rowsaffected
	}
	return 0
}

type BugDeleteRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BugDeleteRequest) Reset()         { *m = BugDeleteRequest{} }
func (m *BugDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*BugDeleteRequest) ProtoMessage()    {}
func (*BugDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_42e24d81e69473d1, []int{8}
}

func (m *BugDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BugDeleteRequest.Unmarshal(m, b)
}
func (m *BugDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BugDeleteRequest.Marshal(b, m, deterministic)
}
func (m *BugDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BugDeleteRequest.Merge(m, src)
}
func (m *BugDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_BugDeleteRequest.Size(m)
}
func (m *BugDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BugDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BugDeleteRequest proto.InternalMessageInfo

func (m *BugDeleteRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type BugDeleteResponse struct {
	Rowsaffected         int64    `protobuf:"varint,1,opt,name=rowsaffected,proto3" json:"rowsaffected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BugDeleteResponse) Reset()         { *m = BugDeleteResponse{} }
func (m *BugDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*BugDeleteResponse) ProtoMessage()    {}
func (*BugDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_42e24d81e69473d1, []int{9}
}

func (m *BugDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BugDeleteResponse.Unmarshal(m, b)
}
func (m *BugDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BugDeleteResponse.Marshal(b, m, deterministic)
}
func (m *BugDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BugDeleteResponse.Merge(m, src)
}
func (m *BugDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_BugDeleteResponse.Size(m)
}
func (m *BugDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BugDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BugDeleteResponse proto.InternalMessageInfo

func (m *BugDeleteResponse) GetRowsaffected() int64 {
	if m != nil {
		return m.Rowsaffected
	}
	return 0
}

type BugPatchRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BugPatchRequest) Reset()         { *m = BugPatchRequest{} }
func (m *BugPatchRequest) String() string { return proto.CompactTextString(m) }
func (*BugPatchRequest) ProtoMessage()    {}
func (*BugPatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_42e24d81e69473d1, []int{10}
}

func (m *BugPatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BugPatchRequest.Unmarshal(m, b)
}
func (m *BugPatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BugPatchRequest.Marshal(b, m, deterministic)
}
func (m *BugPatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BugPatchRequest.Merge(m, src)
}
func (m *BugPatchRequest) XXX_Size() int {
	return xxx_messageInfo_BugPatchRequest.Size(m)
}
func (m *BugPatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BugPatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BugPatchRequest proto.InternalMessageInfo

func (m *BugPatchRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BugPatchRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *BugPatchRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type BugPatchResponse struct {
	Rowsaffected         int64    `protobuf:"varint,1,opt,name=rowsaffected,proto3" json:"rowsaffected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BugPatchResponse) Reset()         { *m = BugPatchResponse{} }
func (m *BugPatchResponse) String() string { return proto.CompactTextString(m) }
func (*BugPatchResponse) ProtoMessage()    {}
func (*BugPatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_42e24d81e69473d1, []int{11}
}

func (m *BugPatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BugPatchResponse.Unmarshal(m, b)
}
func (m *BugPatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BugPatchResponse.Marshal(b, m, deterministic)
}
func (m *BugPatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BugPatchResponse.Merge(m, src)
}
func (m *BugPatchResponse) XXX_Size() int {
	return xxx_messageInfo_BugPatchResponse.Size(m)
}
func (m *BugPatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BugPatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BugPatchResponse proto.InternalMessageInfo

func (m *BugPatchResponse) GetRowsaffected() int64 {
	if m != nil {
		return m.Rowsaffected
	}
	return 0
}

func init() {
	proto.RegisterType((*BugSearchRequest)(nil), "pb.BugSearchRequest")
	proto.RegisterMapType((map[string]string)(nil), "pb.BugSearchRequest.ValuesEntry")
	proto.RegisterType((*BugSearchResponse)(nil), "pb.BugSearchResponse")
	proto.RegisterType((*BugCreateRequest)(nil), "pb.BugCreateRequest")
	proto.RegisterMapType((map[string]string)(nil), "pb.BugCreateRequest.ValuesEntry")
	proto.RegisterType((*BugCreateResponse)(nil), "pb.BugCreateResponse")
	proto.RegisterType((*BugReadRequest)(nil), "pb.BugReadRequest")
	proto.RegisterType((*BugReadResponse)(nil), "pb.BugReadResponse")
	proto.RegisterType((*BugUpdateRequest)(nil), "pb.BugUpdateRequest")
	proto.RegisterMapType((map[string]string)(nil), "pb.BugUpdateRequest.ValuesEntry")
	proto.RegisterType((*BugUpdateResponse)(nil), "pb.BugUpdateResponse")
	proto.RegisterType((*BugDeleteRequest)(nil), "pb.BugDeleteRequest")
	proto.RegisterType((*BugDeleteResponse)(nil), "pb.BugDeleteResponse")
	proto.RegisterType((*BugPatchRequest)(nil), "pb.BugPatchRequest")
	proto.RegisterType((*BugPatchResponse)(nil), "pb.BugPatchResponse")
}

func init() {
	proto.RegisterFile("proto/bug_service.proto", fileDescriptor_42e24d81e69473d1)
}

var fileDescriptor_42e24d81e69473d1 = []byte{
	// 993 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x96, 0x4f, 0x6f, 0x1b, 0x45,
	0x18, 0xc6, 0x99, 0x75, 0x93, 0xd4, 0x63, 0xd7, 0x4d, 0x87, 0x14, 0xcc, 0x52, 0x89, 0xe9, 0x1a,
	0x24, 0xb7, 0x4a, 0xed, 0x60, 0x94, 0x92, 0x46, 0xa1, 0x92, 0x4b, 0x83, 0x94, 0x5e, 0xa8, 0xcc,
	0x9f, 0x2b, 0x9a, 0xf5, 0xce, 0x6e, 0x46, 0xdd, 0xec, 0x6c, 0x77, 0x66, 0x63, 0x59, 0x15, 0x17,
	0x24, 0xc4, 0x15, 0x19, 0x24, 0xc4, 0x0d, 0x24, 0x8e, 0x1c, 0x39, 0x81, 0x90, 0xf8, 0x0e, 0xf0,
	0x11, 0x90, 0x38, 0x50, 0x8e, 0x70, 0x46, 0x3b, 0xb3, 0xbb, 0xd9, 0xb1, 0x1d, 0x44, 0x44, 0x38,
	0xc5, 0xf3, 0xe8, 0xdd, 0x99, 0xf7, 0xf7, 0xcc, 0x3b, 0x8f, 0x02, 0x9f, 0x8f, 0x13, 0x2e, 0x79,
	0xdf, 0x4d, 0x83, 0x0f, 0x04, 0x4d, 0x8e, 0xd9, 0x98, 0xf6, 0x94, 0x82, 0xac, 0xd8, 0xb5, 0xaf,
	0x05, 0x9c, 0x07, 0x21, 0xed, 0x93, 0x98, 0xf5, 0x49, 0x14, 0x71, 0x49, 0x24, 0xe3, 0x91, 0xd0,
	0x15, 0xf6, 0xa6, 0xfa, 0x33, 0xbe, 0x15, 0xd0, 0xe8, 0x96, 0x98, 0x90, 0x20, 0xa0, 0x49, 0x9f,
	0xc7, 0xaa, 0x62, 0x49, 0xf5, 0xe5, 0xf2, 0x20, 0x2d, 0x38, 0x7f, 0x00, 0xb8, 0x7e, 0x2f, 0x0d,
	0xde, 0xa1, 0x24, 0x19, 0x1f, 0x8e, 0xe8, 0xe3, 0x94, 0x0a, 0x89, 0x76, 0xe0, 0xea, 0x31, 0x09,
	0x53, 0x2a, 0xda, 0x00, 0xd7, 0xba, 0x8d, 0x01, 0xee, 0xc5, 0x6e, 0x6f, 0xbe, 0xaa, 0xf7, 0xbe,
	0x2a, 0xd9, 0x8f, 0x64, 0x32, 0x1d, 0xe5, 0xf5, 0x68, 0x03, 0xae, 0x84, 0xec, 0x88, 0xc9, 0xb6,
	0x85, 0x41, 0xb7, 0x36, 0xd2, 0x0b, 0xf4, 0x1c, 0x5c, 0xe5, 0xbe, 0x2f, 0xa8, 0x6c, 0xd7, 0x94,
	0x9c, 0xaf, 0x50, 0x1b, 0xae, 0xf1, 0xc4, 0xa3, 0x89, 0x3b, 0x6d, 0x5f, 0xc0, 0xa0, 0x5b, 0x1f,
	0x15, 0x4b, 0x74, 0x0d, 0xd6, 0xd5, 0x4f, 0x8f, 0x8a, 0x71, 0x7b, 0x05, 0x83, 0xee, 0xc5, 0xd1,
	0x89, 0x60, 0xdf, 0x81, 0x8d, 0xca, 0xe1, 0x68, 0x1d, 0xd6, 0x1e, 0xd1, 0x69, 0x1b, 0xa8, 0x2d,
	0xb2, 0x9f, 0x59, 0x1b, 0xaa, 0x21, 0xd5, 0x46, 0x7d, 0xa4, 0x17, 0xbb, 0xd6, 0x0e, 0x70, 0xde,
	0x82, 0x57, 0x2a, 0x20, 0x22, 0xe6, 0x91, 0xa0, 0xe8, 0x45, 0x78, 0xe1, 0x5e, 0x1a, 0x14, 0xb4,
	0x6b, 0x39, 0xed, 0x48, 0x89, 0xd9, 0x5e, 0x92, 0x4b, 0x12, 0x16, 0x48, 0x6a, 0xe1, 0x7c, 0xa2,
	0x7d, 0x7b, 0x33, 0xa1, 0x44, 0xd2, 0x45, 0xdf, 0x2c, 0xc3, 0x37, 0xa3, 0x6a, 0x99, 0x6f, 0xff,
	0x85, 0xa8, 0xa3, 0x88, 0x8a, 0x23, 0x72, 0xa2, 0x16, 0xb4, 0x98, 0xa7, 0xbe, 0xaf, 0x8d, 0x2c,
	0xe6, 0x39, 0x18, 0xb6, 0x32, 0x22, 0x4a, 0xbc, 0xa2, 0xd7, 0xf9, 0x8a, 0x4d, 0x78, 0xb9, 0xac,
	0xc8, 0x37, 0x79, 0x01, 0xd6, 0xdc, 0x34, 0x50, 0x35, 0x15, 0x57, 0x32, 0xcd, 0xf9, 0x42, 0xe3,
	0xbf, 0x17, 0x7b, 0x15, 0xfc, 0xb9, 0x2d, 0x4f, 0xb5, 0xc3, 0xf8, 0xea, 0xbc, 0xed, 0x78, 0x5d,
	0xd9, 0x51, 0x1c, 0x91, 0x93, 0x38, 0xb0, 0x99, 0xf0, 0x89, 0x20, 0xbe, 0x4f, 0xc7, 0x92, 0x16,
	0x3d, 0x1a, 0x9a, 0xe3, 0x28, 0xa2, 0xfb, 0x34, 0xa4, 0xa7, 0x12, 0xe5, 0x9b, 0x17, 0x35, 0x67,
	0xd8, 0xfc, 0x40, 0xb9, 0xfb, 0x90, 0xc8, 0x93, 0x47, 0x36, 0xef, 0x56, 0x0e, 0x69, 0x2d, 0x81,
	0xac, 0x55, 0x20, 0x9d, 0xdb, 0xaa, 0xcf, 0x7c, 0xab, 0x7f, 0xdf, 0xc2, 0xe0, 0xc7, 0x26, 0x84,
	0x6a, 0xf4, 0x55, 0xbe, 0xa0, 0x9f, 0x2c, 0x58, 0x2f, 0x5f, 0x02, 0xda, 0x58, 0xf6, 0xc2, 0xed,
	0xab, 0x73, 0xaa, 0x3e, 0xcd, 0xf9, 0xd8, 0x9a, 0x0d, 0x7f, 0x07, 0xa8, 0xa1, 0x65, 0xec, 0xa6,
	0x81, 0xb0, 0x3f, 0x05, 0xf9, 0x8a, 0x8c, 0xc7, 0x3c, 0x8d, 0xa4, 0xc0, 0x13, 0x26, 0x0f, 0x71,
	0x9c, 0xf0, 0x63, 0xe6, 0x51, 0x0f, 0xeb, 0x8b, 0xed, 0xc1, 0x03, 0x1f, 0x4f, 0x79, 0x9a, 0x60,
	0x3e, 0x89, 0x8a, 0x52, 0x7c, 0x70, 0x7f, 0x13, 0x93, 0x30, 0xe4, 0x13, 0xea, 0x61, 0x22, 0x31,
	0x89, 0xa6, 0x58, 0x48, 0x22, 0x53, 0xd1, 0x83, 0x6f, 0xcb, 0x43, 0x9a, 0x4c, 0x98, 0xa0, 0x9b,
	0x38, 0xa6, 0xc9, 0x11, 0x13, 0x82, 0xf1, 0x08, 0xbb, 0x44, 0x50, 0x0f, 0xf3, 0x68, 0x17, 0x77,
	0x62, 0x2a, 0x59, 0x16, 0x70, 0x2c, 0xf2, 0x39, 0xee, 0x7a, 0xd4, 0x27, 0x69, 0x28, 0x77, 0xf1,
	0x60, 0xeb, 0xc6, 0x83, 0x3d, 0x58, 0x1b, 0x6c, 0x6d, 0xa1, 0x6d, 0xd8, 0xcc, 0x3a, 0xc4, 0x1e,
	0x95, 0x84, 0x85, 0x02, 0xbd, 0x02, 0x3b, 0xf6, 0xf5, 0x4e, 0xdf, 0xa3, 0x3e, 0x8b, 0x98, 0xce,
	0xc9, 0xd8, 0x5d, 0x80, 0x74, 0x1b, 0xb0, 0x0e, 0x57, 0xde, 0xe5, 0x8f, 0x68, 0x84, 0x9e, 0xf9,
	0xe8, 0xe7, 0x5f, 0x3f, 0xb3, 0xd6, 0x51, 0xab, 0x7f, 0xfc, 0x6a, 0x16, 0x9d, 0x7d, 0xa1, 0x4d,
	0xfb, 0x13, 0x28, 0x0b, 0xf5, 0xd3, 0x2b, 0x2d, 0x34, 0x1e, 0x7b, 0x69, 0xa1, 0xf9, 0x3e, 0x9d,
	0xef, 0xc1, 0x6c, 0xf8, 0x0d, 0x40, 0xeb, 0x5a, 0xc6, 0x04, 0x47, 0x74, 0x92, 0x19, 0x69, 0xef,
	0xcd, 0x2b, 0x3d, 0xf8, 0x70, 0x29, 0xf8, 0xd1, 0x54, 0x3c, 0x0e, 0xab, 0xc4, 0xdb, 0xdb, 0x37,
	0x1e, 0xec, 0x6b, 0xe4, 0xbb, 0xf0, 0x2a, 0xf3, 0x30, 0xf7, 0x8b, 0x3d, 0xf0, 0x58, 0x6d, 0xea,
	0x9d, 0xca, 0x6e, 0x76, 0xb7, 0xc8, 0xde, 0x74, 0xd6, 0x72, 0xf6, 0x5d, 0x70, 0x13, 0x7d, 0x6d,
	0xc1, 0xb5, 0x3c, 0x2b, 0x10, 0x2a, 0x62, 0xe1, 0x24, 0x5a, 0xec, 0x67, 0x0d, 0x2d, 0x27, 0x7e,
	0x0a, 0x66, 0xc3, 0x5f, 0x00, 0xba, 0x94, 0x89, 0xaa, 0xa7, 0xec, 0xc6, 0xec, 0x27, 0xe5, 0x32,
	0xbf, 0x9e, 0x73, 0x9e, 0x90, 0x7f, 0x1c, 0x90, 0x3b, 0xda, 0xad, 0x01, 0x6c, 0x54, 0x1a, 0x40,
	0x1d, 0x78, 0xdd, 0x7e, 0x69, 0x89, 0x47, 0x55, 0x9a, 0x45, 0x87, 0x5a, 0xa8, 0x59, 0x4c, 0xc7,
	0x13, 0xe6, 0x7d, 0x88, 0xfe, 0xd2, 0xb3, 0xa1, 0x73, 0xa8, 0x9c, 0x0d, 0x23, 0xf9, 0xca, 0xd9,
	0x30, 0xc3, 0xca, 0xf9, 0x01, 0xcc, 0x86, 0x5f, 0x01, 0x84, 0xb4, 0x5c, 0x35, 0xc7, 0xbe, 0xbb,
	0xa8, 0x9d, 0x69, 0x3e, 0xde, 0xd0, 0xc4, 0xb7, 0xe1, 0xa5, 0x2c, 0x1a, 0x70, 0x91, 0x0d, 0xa7,
	0xce, 0x85, 0xd9, 0xd9, 0x22, 0xf5, 0x15, 0xdb, 0xa0, 0xce, 0x86, 0xe3, 0x37, 0x0d, 0xae, 0x33,
	0xb2, 0x04, 0x37, 0x62, 0xb5, 0x04, 0x37, 0x83, 0xd4, 0xf9, 0x16, 0xcc, 0x86, 0x9f, 0x03, 0xd4,
	0xd4, 0x32, 0x26, 0xea, 0x41, 0xec, 0x54, 0x57, 0xff, 0x2b, 0xac, 0xd9, 0xcd, 0x92, 0x2b, 0xbe,
	0x69, 0x5e, 0xf1, 0x53, 0x00, 0x2f, 0x16, 0x49, 0x8c, 0x8a, 0x99, 0xaf, 0x46, 0xbc, 0xbd, 0x61,
	0x8a, 0x39, 0xe6, 0x77, 0x60, 0x36, 0xfc, 0x12, 0xa0, 0xd6, 0xbe, 0xc7, 0xa4, 0xba, 0x49, 0x9f,
	0xd1, 0xd0, 0xb3, 0xf7, 0xd4, 0x9a, 0x9c, 0x28, 0x67, 0x82, 0x2d, 0xc3, 0x6e, 0x0e, 0xf6, 0x65,
	0xe8, 0xd8, 0x78, 0x09, 0xac, 0xd1, 0xd2, 0x92, 0x8b, 0x1d, 0xcc, 0x5f, 0xac, 0xbb, 0xaa, 0xfe,
	0x61, 0x7c, 0xed, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8e, 0xf2, 0xbd, 0x33, 0xac, 0x0a, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BugServiceClient is the client API for BugService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BugServiceClient interface {
	BugSearch(ctx context.Context, in *BugSearchRequest, opts ...grpc.CallOption) (*BugSearchResponse, error)
	BugCreate(ctx context.Context, in *BugCreateRequest, opts ...grpc.CallOption) (*BugCreateResponse, error)
	BugRead(ctx context.Context, in *BugReadRequest, opts ...grpc.CallOption) (*BugReadResponse, error)
	BugUpdate(ctx context.Context, in *BugUpdateRequest, opts ...grpc.CallOption) (*BugUpdateResponse, error)
	BugDelete(ctx context.Context, in *BugDeleteRequest, opts ...grpc.CallOption) (*BugDeleteResponse, error)
	BugPatch(ctx context.Context, in *BugPatchRequest, opts ...grpc.CallOption) (*BugPatchResponse, error)
}

type bugServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBugServiceClient(cc grpc.ClientConnInterface) BugServiceClient {
	return &bugServiceClient{cc}
}

func (c *bugServiceClient) BugSearch(ctx context.Context, in *BugSearchRequest, opts ...grpc.CallOption) (*BugSearchResponse, error) {
	out := new(BugSearchResponse)
	err := c.cc.Invoke(ctx, "/pb.BugService/BugSearch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bugServiceClient) BugCreate(ctx context.Context, in *BugCreateRequest, opts ...grpc.CallOption) (*BugCreateResponse, error) {
	out := new(BugCreateResponse)
	err := c.cc.Invoke(ctx, "/pb.BugService/BugCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bugServiceClient) BugRead(ctx context.Context, in *BugReadRequest, opts ...grpc.CallOption) (*BugReadResponse, error) {
	out := new(BugReadResponse)
	err := c.cc.Invoke(ctx, "/pb.BugService/BugRead", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bugServiceClient) BugUpdate(ctx context.Context, in *BugUpdateRequest, opts ...grpc.CallOption) (*BugUpdateResponse, error) {
	out := new(BugUpdateResponse)
	err := c.cc.Invoke(ctx, "/pb.BugService/BugUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bugServiceClient) BugDelete(ctx context.Context, in *BugDeleteRequest, opts ...grpc.CallOption) (*BugDeleteResponse, error) {
	out := new(BugDeleteResponse)
	err := c.cc.Invoke(ctx, "/pb.BugService/BugDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bugServiceClient) BugPatch(ctx context.Context, in *BugPatchRequest, opts ...grpc.CallOption) (*BugPatchResponse, error) {
	out := new(BugPatchResponse)
	err := c.cc.Invoke(ctx, "/pb.BugService/BugPatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BugServiceServer is the server API for BugService service.
type BugServiceServer interface {
	BugSearch(context.Context, *BugSearchRequest) (*BugSearchResponse, error)
	BugCreate(context.Context, *BugCreateRequest) (*BugCreateResponse, error)
	BugRead(context.Context, *BugReadRequest) (*BugReadResponse, error)
	BugUpdate(context.Context, *BugUpdateRequest) (*BugUpdateResponse, error)
	BugDelete(context.Context, *BugDeleteRequest) (*BugDeleteResponse, error)
	BugPatch(context.Context, *BugPatchRequest) (*BugPatchResponse, error)
}

// UnimplementedBugServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBugServiceServer struct {
}

func (*UnimplementedBugServiceServer) BugSearch(ctx context.Context, req *BugSearchRequest) (*BugSearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BugSearch not implemented")
}
func (*UnimplementedBugServiceServer) BugCreate(ctx context.Context, req *BugCreateRequest) (*BugCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BugCreate not implemented")
}
func (*UnimplementedBugServiceServer) BugRead(ctx context.Context, req *BugReadRequest) (*BugReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BugRead not implemented")
}
func (*UnimplementedBugServiceServer) BugUpdate(ctx context.Context, req *BugUpdateRequest) (*BugUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BugUpdate not implemented")
}
func (*UnimplementedBugServiceServer) BugDelete(ctx context.Context, req *BugDeleteRequest) (*BugDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BugDelete not implemented")
}
func (*UnimplementedBugServiceServer) BugPatch(ctx context.Context, req *BugPatchRequest) (*BugPatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BugPatch not implemented")
}

func RegisterBugServiceServer(s *grpc.Server, srv BugServiceServer) {
	s.RegisterService(&_BugService_serviceDesc, srv)
}

func _BugService_BugSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BugSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BugServiceServer).BugSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BugService/BugSearch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BugServiceServer).BugSearch(ctx, req.(*BugSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BugService_BugCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BugCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BugServiceServer).BugCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BugService/BugCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BugServiceServer).BugCreate(ctx, req.(*BugCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BugService_BugRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BugReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BugServiceServer).BugRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BugService/BugRead",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BugServiceServer).BugRead(ctx, req.(*BugReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BugService_BugUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BugUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BugServiceServer).BugUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BugService/BugUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BugServiceServer).BugUpdate(ctx, req.(*BugUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BugService_BugDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BugDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BugServiceServer).BugDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BugService/BugDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BugServiceServer).BugDelete(ctx, req.(*BugDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BugService_BugPatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BugPatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BugServiceServer).BugPatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BugService/BugPatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BugServiceServer).BugPatch(ctx, req.(*BugPatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BugService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.BugService",
	HandlerType: (*BugServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BugSearch",
			Handler:    _BugService_BugSearch_Handler,
		},
		{
			MethodName: "BugCreate",
			Handler:    _BugService_BugCreate_Handler,
		},
		{
			MethodName: "BugRead",
			Handler:    _BugService_BugRead_Handler,
		},
		{
			MethodName: "BugUpdate",
			Handler:    _BugService_BugUpdate_Handler,
		},
		{
			MethodName: "BugDelete",
			Handler:    _BugService_BugDelete_Handler,
		},
		{
			MethodName: "BugPatch",
			Handler:    _BugService_BugPatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/bug_service.proto",
}
