// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/class.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Class struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon                 string   `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Bit                  int64    `protobuf:"varint,4,opt,name=bit,proto3" json:"bit,omitempty"`
	ShortName            string   `protobuf:"bytes,5,opt,name=short_name,json=shortName,proto3" json:"short_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Class) Reset()         { *m = Class{} }
func (m *Class) String() string { return proto.CompactTextString(m) }
func (*Class) ProtoMessage()    {}
func (*Class) Descriptor() ([]byte, []int) {
	return fileDescriptor_edeb0c4bc192e26e, []int{0}
}

func (m *Class) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Class.Unmarshal(m, b)
}
func (m *Class) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Class.Marshal(b, m, deterministic)
}
func (m *Class) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Class.Merge(m, src)
}
func (m *Class) XXX_Size() int {
	return xxx_messageInfo_Class.Size(m)
}
func (m *Class) XXX_DiscardUnknown() {
	xxx_messageInfo_Class.DiscardUnknown(m)
}

var xxx_messageInfo_Class proto.InternalMessageInfo

func (m *Class) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Class) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Class) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *Class) GetBit() int64 {
	if m != nil {
		return m.Bit
	}
	return 0
}

func (m *Class) GetShortName() string {
	if m != nil {
		return m.ShortName
	}
	return ""
}

func init() {
	proto.RegisterType((*Class)(nil), "pb.Class")
}

func init() { proto.RegisterFile("proto/class.proto", fileDescriptor_edeb0c4bc192e26e) }

var fileDescriptor_edeb0c4bc192e26e = []byte{
	// 135 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xce, 0x49, 0x2c, 0x2e, 0xd6, 0x03, 0xb3, 0x85, 0x98, 0x0a, 0x92, 0x94, 0x0a,
	0xb8, 0x58, 0x9d, 0x41, 0x42, 0x42, 0x7c, 0x5c, 0x4c, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a,
	0xcc, 0x41, 0x4c, 0x99, 0x29, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x4c, 0x0a,
	0x8c, 0x1a, 0x9c, 0x41, 0x60, 0x36, 0x48, 0x2c, 0x33, 0x39, 0x3f, 0x4f, 0x82, 0x19, 0x22, 0x06,
	0x62, 0x0b, 0x09, 0x70, 0x31, 0x27, 0x65, 0x96, 0x48, 0xb0, 0x80, 0x35, 0x82, 0x98, 0x42, 0xb2,
	0x5c, 0x5c, 0xc5, 0x19, 0xf9, 0x45, 0x25, 0xf1, 0x60, 0xfd, 0xac, 0x60, 0xb5, 0x9c, 0x60, 0x11,
	0xbf, 0xc4, 0xdc, 0xd4, 0x24, 0x36, 0xb0, 0xe5, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7e,
	0x13, 0xe3, 0x7c, 0x91, 0x00, 0x00, 0x00,
}
