// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/handin_service.proto

package pb

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HandinSearchRequest struct {
	Values               map[string]string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Limit                int64             `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int64             `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Orderby              string            `protobuf:"bytes,4,opt,name=orderby,proto3" json:"orderby,omitempty"`
	Orderdesc            bool              `protobuf:"varint,5,opt,name=orderdesc,proto3" json:"orderdesc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *HandinSearchRequest) Reset()         { *m = HandinSearchRequest{} }
func (m *HandinSearchRequest) String() string { return proto.CompactTextString(m) }
func (*HandinSearchRequest) ProtoMessage()    {}
func (*HandinSearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_751de55a9220f1f4, []int{0}
}

func (m *HandinSearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandinSearchRequest.Unmarshal(m, b)
}
func (m *HandinSearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandinSearchRequest.Marshal(b, m, deterministic)
}
func (m *HandinSearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandinSearchRequest.Merge(m, src)
}
func (m *HandinSearchRequest) XXX_Size() int {
	return xxx_messageInfo_HandinSearchRequest.Size(m)
}
func (m *HandinSearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HandinSearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HandinSearchRequest proto.InternalMessageInfo

func (m *HandinSearchRequest) GetValues() map[string]string {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *HandinSearchRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *HandinSearchRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *HandinSearchRequest) GetOrderby() string {
	if m != nil {
		return m.Orderby
	}
	return ""
}

func (m *HandinSearchRequest) GetOrderdesc() bool {
	if m != nil {
		return m.Orderdesc
	}
	return false
}

type HandinSearchResponse struct {
	Handins              []*Handin `protobuf:"bytes,1,rep,name=Handins,proto3" json:"Handins,omitempty"`
	Total                int64     `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *HandinSearchResponse) Reset()         { *m = HandinSearchResponse{} }
func (m *HandinSearchResponse) String() string { return proto.CompactTextString(m) }
func (*HandinSearchResponse) ProtoMessage()    {}
func (*HandinSearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_751de55a9220f1f4, []int{1}
}

func (m *HandinSearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandinSearchResponse.Unmarshal(m, b)
}
func (m *HandinSearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandinSearchResponse.Marshal(b, m, deterministic)
}
func (m *HandinSearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandinSearchResponse.Merge(m, src)
}
func (m *HandinSearchResponse) XXX_Size() int {
	return xxx_messageInfo_HandinSearchResponse.Size(m)
}
func (m *HandinSearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HandinSearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HandinSearchResponse proto.InternalMessageInfo

func (m *HandinSearchResponse) GetHandins() []*Handin {
	if m != nil {
		return m.Handins
	}
	return nil
}

func (m *HandinSearchResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type HandinCreateRequest struct {
	Values               map[string]string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *HandinCreateRequest) Reset()         { *m = HandinCreateRequest{} }
func (m *HandinCreateRequest) String() string { return proto.CompactTextString(m) }
func (*HandinCreateRequest) ProtoMessage()    {}
func (*HandinCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_751de55a9220f1f4, []int{2}
}

func (m *HandinCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandinCreateRequest.Unmarshal(m, b)
}
func (m *HandinCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandinCreateRequest.Marshal(b, m, deterministic)
}
func (m *HandinCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandinCreateRequest.Merge(m, src)
}
func (m *HandinCreateRequest) XXX_Size() int {
	return xxx_messageInfo_HandinCreateRequest.Size(m)
}
func (m *HandinCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HandinCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HandinCreateRequest proto.InternalMessageInfo

func (m *HandinCreateRequest) GetValues() map[string]string {
	if m != nil {
		return m.Values
	}
	return nil
}

type HandinCreateResponse struct {
	Handinid             int64    `protobuf:"varint,1,opt,name=handinid,proto3" json:"handinid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandinCreateResponse) Reset()         { *m = HandinCreateResponse{} }
func (m *HandinCreateResponse) String() string { return proto.CompactTextString(m) }
func (*HandinCreateResponse) ProtoMessage()    {}
func (*HandinCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_751de55a9220f1f4, []int{3}
}

func (m *HandinCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandinCreateResponse.Unmarshal(m, b)
}
func (m *HandinCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandinCreateResponse.Marshal(b, m, deterministic)
}
func (m *HandinCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandinCreateResponse.Merge(m, src)
}
func (m *HandinCreateResponse) XXX_Size() int {
	return xxx_messageInfo_HandinCreateResponse.Size(m)
}
func (m *HandinCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HandinCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HandinCreateResponse proto.InternalMessageInfo

func (m *HandinCreateResponse) GetHandinid() int64 {
	if m != nil {
		return m.Handinid
	}
	return 0
}

type HandinReadRequest struct {
	Handinid             int64    `protobuf:"varint,1,opt,name=handinid,proto3" json:"handinid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandinReadRequest) Reset()         { *m = HandinReadRequest{} }
func (m *HandinReadRequest) String() string { return proto.CompactTextString(m) }
func (*HandinReadRequest) ProtoMessage()    {}
func (*HandinReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_751de55a9220f1f4, []int{4}
}

func (m *HandinReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandinReadRequest.Unmarshal(m, b)
}
func (m *HandinReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandinReadRequest.Marshal(b, m, deterministic)
}
func (m *HandinReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandinReadRequest.Merge(m, src)
}
func (m *HandinReadRequest) XXX_Size() int {
	return xxx_messageInfo_HandinReadRequest.Size(m)
}
func (m *HandinReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HandinReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HandinReadRequest proto.InternalMessageInfo

func (m *HandinReadRequest) GetHandinid() int64 {
	if m != nil {
		return m.Handinid
	}
	return 0
}

type HandinReadResponse struct {
	Handin               *Handin  `protobuf:"bytes,1,opt,name=handin,proto3" json:"handin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandinReadResponse) Reset()         { *m = HandinReadResponse{} }
func (m *HandinReadResponse) String() string { return proto.CompactTextString(m) }
func (*HandinReadResponse) ProtoMessage()    {}
func (*HandinReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_751de55a9220f1f4, []int{5}
}

func (m *HandinReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandinReadResponse.Unmarshal(m, b)
}
func (m *HandinReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandinReadResponse.Marshal(b, m, deterministic)
}
func (m *HandinReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandinReadResponse.Merge(m, src)
}
func (m *HandinReadResponse) XXX_Size() int {
	return xxx_messageInfo_HandinReadResponse.Size(m)
}
func (m *HandinReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HandinReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HandinReadResponse proto.InternalMessageInfo

func (m *HandinReadResponse) GetHandin() *Handin {
	if m != nil {
		return m.Handin
	}
	return nil
}

type HandinUpdateRequest struct {
	Handinid             int64             `protobuf:"varint,1,opt,name=handinid,proto3" json:"handinid,omitempty"`
	Values               map[string]string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *HandinUpdateRequest) Reset()         { *m = HandinUpdateRequest{} }
func (m *HandinUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*HandinUpdateRequest) ProtoMessage()    {}
func (*HandinUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_751de55a9220f1f4, []int{6}
}

func (m *HandinUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandinUpdateRequest.Unmarshal(m, b)
}
func (m *HandinUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandinUpdateRequest.Marshal(b, m, deterministic)
}
func (m *HandinUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandinUpdateRequest.Merge(m, src)
}
func (m *HandinUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_HandinUpdateRequest.Size(m)
}
func (m *HandinUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HandinUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HandinUpdateRequest proto.InternalMessageInfo

func (m *HandinUpdateRequest) GetHandinid() int64 {
	if m != nil {
		return m.Handinid
	}
	return 0
}

func (m *HandinUpdateRequest) GetValues() map[string]string {
	if m != nil {
		return m.Values
	}
	return nil
}

type HandinUpdateResponse struct {
	Rowsaffected         int64    `protobuf:"varint,1,opt,name=rowsaffected,proto3" json:"rowsaffected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandinUpdateResponse) Reset()         { *m = HandinUpdateResponse{} }
func (m *HandinUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*HandinUpdateResponse) ProtoMessage()    {}
func (*HandinUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_751de55a9220f1f4, []int{7}
}

func (m *HandinUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandinUpdateResponse.Unmarshal(m, b)
}
func (m *HandinUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandinUpdateResponse.Marshal(b, m, deterministic)
}
func (m *HandinUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandinUpdateResponse.Merge(m, src)
}
func (m *HandinUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_HandinUpdateResponse.Size(m)
}
func (m *HandinUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HandinUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HandinUpdateResponse proto.InternalMessageInfo

func (m *HandinUpdateResponse) GetRowsaffected() int64 {
	if m != nil {
		return m.Rowsaffected
	}
	return 0
}

type HandinDeleteRequest struct {
	Handinid             int64    `protobuf:"varint,1,opt,name=handinid,proto3" json:"handinid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandinDeleteRequest) Reset()         { *m = HandinDeleteRequest{} }
func (m *HandinDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*HandinDeleteRequest) ProtoMessage()    {}
func (*HandinDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_751de55a9220f1f4, []int{8}
}

func (m *HandinDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandinDeleteRequest.Unmarshal(m, b)
}
func (m *HandinDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandinDeleteRequest.Marshal(b, m, deterministic)
}
func (m *HandinDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandinDeleteRequest.Merge(m, src)
}
func (m *HandinDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_HandinDeleteRequest.Size(m)
}
func (m *HandinDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HandinDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HandinDeleteRequest proto.InternalMessageInfo

func (m *HandinDeleteRequest) GetHandinid() int64 {
	if m != nil {
		return m.Handinid
	}
	return 0
}

type HandinDeleteResponse struct {
	Rowsaffected         int64    `protobuf:"varint,1,opt,name=rowsaffected,proto3" json:"rowsaffected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandinDeleteResponse) Reset()         { *m = HandinDeleteResponse{} }
func (m *HandinDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*HandinDeleteResponse) ProtoMessage()    {}
func (*HandinDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_751de55a9220f1f4, []int{9}
}

func (m *HandinDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandinDeleteResponse.Unmarshal(m, b)
}
func (m *HandinDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandinDeleteResponse.Marshal(b, m, deterministic)
}
func (m *HandinDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandinDeleteResponse.Merge(m, src)
}
func (m *HandinDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_HandinDeleteResponse.Size(m)
}
func (m *HandinDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HandinDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HandinDeleteResponse proto.InternalMessageInfo

func (m *HandinDeleteResponse) GetRowsaffected() int64 {
	if m != nil {
		return m.Rowsaffected
	}
	return 0
}

type HandinPatchRequest struct {
	Handinid             int64    `protobuf:"varint,1,opt,name=handinid,proto3" json:"handinid,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandinPatchRequest) Reset()         { *m = HandinPatchRequest{} }
func (m *HandinPatchRequest) String() string { return proto.CompactTextString(m) }
func (*HandinPatchRequest) ProtoMessage()    {}
func (*HandinPatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_751de55a9220f1f4, []int{10}
}

func (m *HandinPatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandinPatchRequest.Unmarshal(m, b)
}
func (m *HandinPatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandinPatchRequest.Marshal(b, m, deterministic)
}
func (m *HandinPatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandinPatchRequest.Merge(m, src)
}
func (m *HandinPatchRequest) XXX_Size() int {
	return xxx_messageInfo_HandinPatchRequest.Size(m)
}
func (m *HandinPatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HandinPatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HandinPatchRequest proto.InternalMessageInfo

func (m *HandinPatchRequest) GetHandinid() int64 {
	if m != nil {
		return m.Handinid
	}
	return 0
}

func (m *HandinPatchRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *HandinPatchRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type HandinPatchResponse struct {
	Rowsaffected         int64    `protobuf:"varint,1,opt,name=rowsaffected,proto3" json:"rowsaffected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandinPatchResponse) Reset()         { *m = HandinPatchResponse{} }
func (m *HandinPatchResponse) String() string { return proto.CompactTextString(m) }
func (*HandinPatchResponse) ProtoMessage()    {}
func (*HandinPatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_751de55a9220f1f4, []int{11}
}

func (m *HandinPatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandinPatchResponse.Unmarshal(m, b)
}
func (m *HandinPatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandinPatchResponse.Marshal(b, m, deterministic)
}
func (m *HandinPatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandinPatchResponse.Merge(m, src)
}
func (m *HandinPatchResponse) XXX_Size() int {
	return xxx_messageInfo_HandinPatchResponse.Size(m)
}
func (m *HandinPatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HandinPatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HandinPatchResponse proto.InternalMessageInfo

func (m *HandinPatchResponse) GetRowsaffected() int64 {
	if m != nil {
		return m.Rowsaffected
	}
	return 0
}

func init() {
	proto.RegisterType((*HandinSearchRequest)(nil), "pb.HandinSearchRequest")
	proto.RegisterMapType((map[string]string)(nil), "pb.HandinSearchRequest.ValuesEntry")
	proto.RegisterType((*HandinSearchResponse)(nil), "pb.HandinSearchResponse")
	proto.RegisterType((*HandinCreateRequest)(nil), "pb.HandinCreateRequest")
	proto.RegisterMapType((map[string]string)(nil), "pb.HandinCreateRequest.ValuesEntry")
	proto.RegisterType((*HandinCreateResponse)(nil), "pb.HandinCreateResponse")
	proto.RegisterType((*HandinReadRequest)(nil), "pb.HandinReadRequest")
	proto.RegisterType((*HandinReadResponse)(nil), "pb.HandinReadResponse")
	proto.RegisterType((*HandinUpdateRequest)(nil), "pb.HandinUpdateRequest")
	proto.RegisterMapType((map[string]string)(nil), "pb.HandinUpdateRequest.ValuesEntry")
	proto.RegisterType((*HandinUpdateResponse)(nil), "pb.HandinUpdateResponse")
	proto.RegisterType((*HandinDeleteRequest)(nil), "pb.HandinDeleteRequest")
	proto.RegisterType((*HandinDeleteResponse)(nil), "pb.HandinDeleteResponse")
	proto.RegisterType((*HandinPatchRequest)(nil), "pb.HandinPatchRequest")
	proto.RegisterType((*HandinPatchResponse)(nil), "pb.HandinPatchResponse")
}

func init() { proto.RegisterFile("proto/handin_service.proto", fileDescriptor_751de55a9220f1f4) }

var fileDescriptor_751de55a9220f1f4 = []byte{
	// 604 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x96, 0xed, 0x36, 0x6d, 0x26, 0x45, 0xd0, 0x6d, 0xd3, 0x18, 0xab, 0x48, 0xd1, 0xc2, 0x21,
	0xea, 0x21, 0x56, 0xc3, 0xa5, 0x0d, 0x47, 0x40, 0xe2, 0x88, 0x8c, 0x40, 0x15, 0x42, 0xa2, 0x9b,
	0x78, 0xd3, 0x5a, 0x04, 0xaf, 0xb1, 0xb7, 0x41, 0x11, 0xe2, 0xc2, 0x9d, 0x13, 0x4f, 0xc1, 0xbb,
	0x70, 0xe3, 0x15, 0x78, 0x03, 0x5e, 0x00, 0x65, 0xd7, 0x13, 0xef, 0x36, 0x3f, 0x2a, 0x82, 0x5b,
	0x76, 0x3c, 0xfb, 0x7d, 0xf3, 0x7d, 0xfe, 0xc6, 0x81, 0x20, 0xcb, 0x85, 0x14, 0xe1, 0x25, 0x4b,
	0xe3, 0x24, 0x7d, 0x5b, 0xf0, 0x7c, 0x92, 0x0c, 0x79, 0x57, 0x15, 0x89, 0x9b, 0x0d, 0x82, 0xc3,
	0x0b, 0x21, 0x2e, 0xc6, 0x3c, 0x64, 0x59, 0x12, 0xb2, 0x34, 0x15, 0x92, 0xc9, 0x44, 0xa4, 0x85,
	0xee, 0x08, 0x88, 0x79, 0x5b, 0xd7, 0xe8, 0x6f, 0x07, 0xf6, 0x9e, 0xa9, 0xc2, 0x0b, 0xce, 0xf2,
	0xe1, 0x65, 0xc4, 0x3f, 0x5c, 0xf1, 0x42, 0x92, 0x47, 0x50, 0x9b, 0xb0, 0xf1, 0x15, 0x2f, 0x7c,
	0xa7, 0xed, 0x75, 0x1a, 0xbd, 0xfb, 0xdd, 0x6c, 0xd0, 0x5d, 0xd2, 0xd8, 0x7d, 0xa5, 0xba, 0x9e,
	0xa6, 0x32, 0x9f, 0x46, 0xe5, 0x15, 0xb2, 0x0f, 0x9b, 0xe3, 0xe4, 0x7d, 0x22, 0x7d, 0xb7, 0xed,
	0x74, 0xbc, 0x48, 0x1f, 0xc8, 0x01, 0xd4, 0xc4, 0x68, 0x54, 0x70, 0xe9, 0x7b, 0xaa, 0x5c, 0x9e,
	0x88, 0x0f, 0x5b, 0x22, 0x8f, 0x79, 0x3e, 0x98, 0xfa, 0x1b, 0x6d, 0xa7, 0x53, 0x8f, 0xf0, 0x48,
	0x0e, 0xa1, 0xae, 0x7e, 0xc6, 0xbc, 0x18, 0xfa, 0x9b, 0x6d, 0xa7, 0xb3, 0x1d, 0x55, 0x85, 0xe0,
	0x14, 0x1a, 0x06, 0x39, 0xb9, 0x03, 0xde, 0x3b, 0x3e, 0xf5, 0x1d, 0x05, 0x31, 0xfb, 0x39, 0x1b,
	0x43, 0x0d, 0xa4, 0xc6, 0xa8, 0x47, 0xfa, 0xd0, 0x77, 0x4f, 0x1c, 0x1a, 0xc1, 0xbe, 0xad, 0xa5,
	0xc8, 0x44, 0x5a, 0x70, 0xf2, 0x00, 0xb6, 0x74, 0x1d, 0x65, 0x43, 0x25, 0x3b, 0xc2, 0x47, 0x33,
	0x5c, 0x29, 0x24, 0x1b, 0xa3, 0x3c, 0x75, 0xa0, 0x5f, 0xe7, 0x4e, 0x3e, 0xce, 0x39, 0x93, 0x7c,
	0xd1, 0x49, 0xf7, 0xba, 0x93, 0x56, 0xe3, 0x32, 0x27, 0xff, 0x45, 0x63, 0x0f, 0x35, 0x22, 0x4b,
	0xa9, 0x31, 0x80, 0x6d, 0x9d, 0x80, 0x24, 0x56, 0x40, 0x5e, 0x34, 0x3f, 0xd3, 0x10, 0x76, 0x4b,
	0xb1, 0x9c, 0xc5, 0x28, 0x60, 0xdd, 0x85, 0x13, 0x20, 0xe6, 0x85, 0x92, 0x82, 0x42, 0x4d, 0x77,
	0xa8, 0x7e, 0xdb, 0xc5, 0xf2, 0x09, 0xfd, 0x3e, 0xb7, 0xeb, 0x65, 0x16, 0x1b, 0x76, 0xad, 0x61,
	0x5b, 0x67, 0xa5, 0x05, 0xf2, 0xbf, 0xad, 0xec, 0xa3, 0x95, 0xc8, 0x32, 0xd7, 0xb9, 0x93, 0x8b,
	0x8f, 0x05, 0x1b, 0x8d, 0xf8, 0x50, 0x72, 0x9c, 0xd7, 0xaa, 0xd1, 0x63, 0x94, 0xf9, 0x84, 0x8f,
	0xf9, 0x8d, 0x64, 0x56, 0x74, 0x78, 0xe5, 0x2f, 0xe8, 0xce, 0xf0, 0x85, 0x3c, 0x67, 0xb2, 0xda,
	0xe6, 0x75, 0xa6, 0x96, 0x46, 0xb8, 0x4b, 0x8c, 0xf0, 0x0c, 0x23, 0xe8, 0x29, 0x0a, 0x29, 0x91,
	0x6f, 0x3e, 0x54, 0xef, 0xc7, 0x06, 0xdc, 0xc2, 0x7d, 0x53, 0x9f, 0x2c, 0xf2, 0x06, 0x76, 0xcc,
	0x05, 0x24, 0xad, 0x15, 0x9f, 0x97, 0xc0, 0x5f, 0x7c, 0xa0, 0x89, 0xe9, 0xdd, 0x2f, 0x3f, 0x7f,
	0x7d, 0x73, 0xf7, 0xc8, 0x6e, 0x38, 0x39, 0x2e, 0xbf, 0x69, 0x61, 0xa1, 0xd1, 0xce, 0x10, 0x5d,
	0x47, 0xdf, 0x44, 0xb7, 0x56, 0xce, 0x44, 0xb7, 0xb7, 0x84, 0x36, 0x15, 0xfa, 0x6d, 0x0a, 0x15,
	0x7a, 0xdf, 0x39, 0x22, 0xaf, 0x01, 0xaa, 0xbc, 0x93, 0xa6, 0x91, 0xeb, 0x6a, 0x61, 0x82, 0x83,
	0xeb, 0xe5, 0x12, 0xf3, 0x9e, 0xc2, 0x6c, 0x91, 0xa6, 0x31, 0xf1, 0x27, 0x7c, 0x0f, 0x9f, 0xc9,
	0x10, 0xa7, 0xd6, 0x29, 0x33, 0xa7, 0xb6, 0xd2, 0x6d, 0x4e, 0x6d, 0x07, 0x92, 0xb6, 0x15, 0x43,
	0x10, 0x2c, 0x67, 0x98, 0x09, 0x38, 0x47, 0x12, 0x9d, 0x2d, 0x93, 0xc4, 0x0a, 0xa8, 0x49, 0x62,
	0xc7, 0x10, 0x65, 0x1c, 0xad, 0x90, 0x71, 0x0e, 0x0d, 0x23, 0x27, 0xc4, 0x30, 0xc3, 0x8c, 0x64,
	0xd0, 0x5a, 0xa8, 0xdb, 0x1a, 0x7a, 0x2b, 0x35, 0x0c, 0x6a, 0xea, 0xaf, 0xeb, 0xe1, 0x9f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xa1, 0x4a, 0xc5, 0x05, 0x0e, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// HandinServiceClient is the client API for HandinService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HandinServiceClient interface {
	HandinSearch(ctx context.Context, in *HandinSearchRequest, opts ...grpc.CallOption) (*HandinSearchResponse, error)
	HandinCreate(ctx context.Context, in *HandinCreateRequest, opts ...grpc.CallOption) (*HandinCreateResponse, error)
	HandinRead(ctx context.Context, in *HandinReadRequest, opts ...grpc.CallOption) (*HandinReadResponse, error)
	HandinUpdate(ctx context.Context, in *HandinUpdateRequest, opts ...grpc.CallOption) (*HandinUpdateResponse, error)
	HandinDelete(ctx context.Context, in *HandinDeleteRequest, opts ...grpc.CallOption) (*HandinDeleteResponse, error)
	HandinPatch(ctx context.Context, in *HandinPatchRequest, opts ...grpc.CallOption) (*HandinPatchResponse, error)
}

type handinServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHandinServiceClient(cc grpc.ClientConnInterface) HandinServiceClient {
	return &handinServiceClient{cc}
}

func (c *handinServiceClient) HandinSearch(ctx context.Context, in *HandinSearchRequest, opts ...grpc.CallOption) (*HandinSearchResponse, error) {
	out := new(HandinSearchResponse)
	err := c.cc.Invoke(ctx, "/pb.HandinService/HandinSearch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *handinServiceClient) HandinCreate(ctx context.Context, in *HandinCreateRequest, opts ...grpc.CallOption) (*HandinCreateResponse, error) {
	out := new(HandinCreateResponse)
	err := c.cc.Invoke(ctx, "/pb.HandinService/HandinCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *handinServiceClient) HandinRead(ctx context.Context, in *HandinReadRequest, opts ...grpc.CallOption) (*HandinReadResponse, error) {
	out := new(HandinReadResponse)
	err := c.cc.Invoke(ctx, "/pb.HandinService/HandinRead", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *handinServiceClient) HandinUpdate(ctx context.Context, in *HandinUpdateRequest, opts ...grpc.CallOption) (*HandinUpdateResponse, error) {
	out := new(HandinUpdateResponse)
	err := c.cc.Invoke(ctx, "/pb.HandinService/HandinUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *handinServiceClient) HandinDelete(ctx context.Context, in *HandinDeleteRequest, opts ...grpc.CallOption) (*HandinDeleteResponse, error) {
	out := new(HandinDeleteResponse)
	err := c.cc.Invoke(ctx, "/pb.HandinService/HandinDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *handinServiceClient) HandinPatch(ctx context.Context, in *HandinPatchRequest, opts ...grpc.CallOption) (*HandinPatchResponse, error) {
	out := new(HandinPatchResponse)
	err := c.cc.Invoke(ctx, "/pb.HandinService/HandinPatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HandinServiceServer is the server API for HandinService service.
type HandinServiceServer interface {
	HandinSearch(context.Context, *HandinSearchRequest) (*HandinSearchResponse, error)
	HandinCreate(context.Context, *HandinCreateRequest) (*HandinCreateResponse, error)
	HandinRead(context.Context, *HandinReadRequest) (*HandinReadResponse, error)
	HandinUpdate(context.Context, *HandinUpdateRequest) (*HandinUpdateResponse, error)
	HandinDelete(context.Context, *HandinDeleteRequest) (*HandinDeleteResponse, error)
	HandinPatch(context.Context, *HandinPatchRequest) (*HandinPatchResponse, error)
}

// UnimplementedHandinServiceServer can be embedded to have forward compatible implementations.
type UnimplementedHandinServiceServer struct {
}

func (*UnimplementedHandinServiceServer) HandinSearch(ctx context.Context, req *HandinSearchRequest) (*HandinSearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandinSearch not implemented")
}
func (*UnimplementedHandinServiceServer) HandinCreate(ctx context.Context, req *HandinCreateRequest) (*HandinCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandinCreate not implemented")
}
func (*UnimplementedHandinServiceServer) HandinRead(ctx context.Context, req *HandinReadRequest) (*HandinReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandinRead not implemented")
}
func (*UnimplementedHandinServiceServer) HandinUpdate(ctx context.Context, req *HandinUpdateRequest) (*HandinUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandinUpdate not implemented")
}
func (*UnimplementedHandinServiceServer) HandinDelete(ctx context.Context, req *HandinDeleteRequest) (*HandinDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandinDelete not implemented")
}
func (*UnimplementedHandinServiceServer) HandinPatch(ctx context.Context, req *HandinPatchRequest) (*HandinPatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandinPatch not implemented")
}

func RegisterHandinServiceServer(s *grpc.Server, srv HandinServiceServer) {
	s.RegisterService(&_HandinService_serviceDesc, srv)
}

func _HandinService_HandinSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandinSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandinServiceServer).HandinSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.HandinService/HandinSearch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandinServiceServer).HandinSearch(ctx, req.(*HandinSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HandinService_HandinCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandinCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandinServiceServer).HandinCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.HandinService/HandinCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandinServiceServer).HandinCreate(ctx, req.(*HandinCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HandinService_HandinRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandinReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandinServiceServer).HandinRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.HandinService/HandinRead",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandinServiceServer).HandinRead(ctx, req.(*HandinReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HandinService_HandinUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandinUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandinServiceServer).HandinUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.HandinService/HandinUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandinServiceServer).HandinUpdate(ctx, req.(*HandinUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HandinService_HandinDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandinDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandinServiceServer).HandinDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.HandinService/HandinDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandinServiceServer).HandinDelete(ctx, req.(*HandinDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HandinService_HandinPatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandinPatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandinServiceServer).HandinPatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.HandinService/HandinPatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandinServiceServer).HandinPatch(ctx, req.(*HandinPatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HandinService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.HandinService",
	HandlerType: (*HandinServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandinSearch",
			Handler:    _HandinService_HandinSearch_Handler,
		},
		{
			MethodName: "HandinCreate",
			Handler:    _HandinService_HandinCreate_Handler,
		},
		{
			MethodName: "HandinRead",
			Handler:    _HandinService_HandinRead_Handler,
		},
		{
			MethodName: "HandinUpdate",
			Handler:    _HandinService_HandinUpdate_Handler,
		},
		{
			MethodName: "HandinDelete",
			Handler:    _HandinService_HandinDelete_Handler,
		},
		{
			MethodName: "HandinPatch",
			Handler:    _HandinService_HandinPatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/handin_service.proto",
}
