// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/inventory_service.proto

package pb

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InventorySearchRequest struct {
	Values               map[string]string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Limit                int64             `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int64             `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Orderby              string            `protobuf:"bytes,4,opt,name=orderby,proto3" json:"orderby,omitempty"`
	Orderdesc            bool              `protobuf:"varint,5,opt,name=orderdesc,proto3" json:"orderdesc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *InventorySearchRequest) Reset()         { *m = InventorySearchRequest{} }
func (m *InventorySearchRequest) String() string { return proto.CompactTextString(m) }
func (*InventorySearchRequest) ProtoMessage()    {}
func (*InventorySearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2d7d2d6cd9edf07, []int{0}
}

func (m *InventorySearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InventorySearchRequest.Unmarshal(m, b)
}
func (m *InventorySearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InventorySearchRequest.Marshal(b, m, deterministic)
}
func (m *InventorySearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InventorySearchRequest.Merge(m, src)
}
func (m *InventorySearchRequest) XXX_Size() int {
	return xxx_messageInfo_InventorySearchRequest.Size(m)
}
func (m *InventorySearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InventorySearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InventorySearchRequest proto.InternalMessageInfo

func (m *InventorySearchRequest) GetValues() map[string]string {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *InventorySearchRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *InventorySearchRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *InventorySearchRequest) GetOrderby() string {
	if m != nil {
		return m.Orderby
	}
	return ""
}

func (m *InventorySearchRequest) GetOrderdesc() bool {
	if m != nil {
		return m.Orderdesc
	}
	return false
}

type InventorySearchResponse struct {
	Inventorys           []*Inventory `protobuf:"bytes,1,rep,name=Inventorys,proto3" json:"Inventorys,omitempty"`
	Total                int64        `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *InventorySearchResponse) Reset()         { *m = InventorySearchResponse{} }
func (m *InventorySearchResponse) String() string { return proto.CompactTextString(m) }
func (*InventorySearchResponse) ProtoMessage()    {}
func (*InventorySearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2d7d2d6cd9edf07, []int{1}
}

func (m *InventorySearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InventorySearchResponse.Unmarshal(m, b)
}
func (m *InventorySearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InventorySearchResponse.Marshal(b, m, deterministic)
}
func (m *InventorySearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InventorySearchResponse.Merge(m, src)
}
func (m *InventorySearchResponse) XXX_Size() int {
	return xxx_messageInfo_InventorySearchResponse.Size(m)
}
func (m *InventorySearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InventorySearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InventorySearchResponse proto.InternalMessageInfo

func (m *InventorySearchResponse) GetInventorys() []*Inventory {
	if m != nil {
		return m.Inventorys
	}
	return nil
}

func (m *InventorySearchResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type InventoryCreateRequest struct {
	Charid               int64             `protobuf:"varint,1,opt,name=charid,proto3" json:"charid,omitempty"`
	Slotid               int64             `protobuf:"varint,2,opt,name=slotid,proto3" json:"slotid,omitempty"`
	Values               map[string]string `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *InventoryCreateRequest) Reset()         { *m = InventoryCreateRequest{} }
func (m *InventoryCreateRequest) String() string { return proto.CompactTextString(m) }
func (*InventoryCreateRequest) ProtoMessage()    {}
func (*InventoryCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2d7d2d6cd9edf07, []int{2}
}

func (m *InventoryCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InventoryCreateRequest.Unmarshal(m, b)
}
func (m *InventoryCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InventoryCreateRequest.Marshal(b, m, deterministic)
}
func (m *InventoryCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InventoryCreateRequest.Merge(m, src)
}
func (m *InventoryCreateRequest) XXX_Size() int {
	return xxx_messageInfo_InventoryCreateRequest.Size(m)
}
func (m *InventoryCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InventoryCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InventoryCreateRequest proto.InternalMessageInfo

func (m *InventoryCreateRequest) GetCharid() int64 {
	if m != nil {
		return m.Charid
	}
	return 0
}

func (m *InventoryCreateRequest) GetSlotid() int64 {
	if m != nil {
		return m.Slotid
	}
	return 0
}

func (m *InventoryCreateRequest) GetValues() map[string]string {
	if m != nil {
		return m.Values
	}
	return nil
}

type InventoryCreateResponse struct {
	Charid               int64    `protobuf:"varint,1,opt,name=charid,proto3" json:"charid,omitempty"`
	Slotid               int64    `protobuf:"varint,2,opt,name=slotid,proto3" json:"slotid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InventoryCreateResponse) Reset()         { *m = InventoryCreateResponse{} }
func (m *InventoryCreateResponse) String() string { return proto.CompactTextString(m) }
func (*InventoryCreateResponse) ProtoMessage()    {}
func (*InventoryCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2d7d2d6cd9edf07, []int{3}
}

func (m *InventoryCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InventoryCreateResponse.Unmarshal(m, b)
}
func (m *InventoryCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InventoryCreateResponse.Marshal(b, m, deterministic)
}
func (m *InventoryCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InventoryCreateResponse.Merge(m, src)
}
func (m *InventoryCreateResponse) XXX_Size() int {
	return xxx_messageInfo_InventoryCreateResponse.Size(m)
}
func (m *InventoryCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InventoryCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InventoryCreateResponse proto.InternalMessageInfo

func (m *InventoryCreateResponse) GetCharid() int64 {
	if m != nil {
		return m.Charid
	}
	return 0
}

func (m *InventoryCreateResponse) GetSlotid() int64 {
	if m != nil {
		return m.Slotid
	}
	return 0
}

type InventoryReadRequest struct {
	Charid               int64    `protobuf:"varint,1,opt,name=charid,proto3" json:"charid,omitempty"`
	Slotid               int64    `protobuf:"varint,2,opt,name=slotid,proto3" json:"slotid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InventoryReadRequest) Reset()         { *m = InventoryReadRequest{} }
func (m *InventoryReadRequest) String() string { return proto.CompactTextString(m) }
func (*InventoryReadRequest) ProtoMessage()    {}
func (*InventoryReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2d7d2d6cd9edf07, []int{4}
}

func (m *InventoryReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InventoryReadRequest.Unmarshal(m, b)
}
func (m *InventoryReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InventoryReadRequest.Marshal(b, m, deterministic)
}
func (m *InventoryReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InventoryReadRequest.Merge(m, src)
}
func (m *InventoryReadRequest) XXX_Size() int {
	return xxx_messageInfo_InventoryReadRequest.Size(m)
}
func (m *InventoryReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InventoryReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InventoryReadRequest proto.InternalMessageInfo

func (m *InventoryReadRequest) GetCharid() int64 {
	if m != nil {
		return m.Charid
	}
	return 0
}

func (m *InventoryReadRequest) GetSlotid() int64 {
	if m != nil {
		return m.Slotid
	}
	return 0
}

type InventoryReadResponse struct {
	Inventory            *Inventory `protobuf:"bytes,1,opt,name=inventory,proto3" json:"inventory,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *InventoryReadResponse) Reset()         { *m = InventoryReadResponse{} }
func (m *InventoryReadResponse) String() string { return proto.CompactTextString(m) }
func (*InventoryReadResponse) ProtoMessage()    {}
func (*InventoryReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2d7d2d6cd9edf07, []int{5}
}

func (m *InventoryReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InventoryReadResponse.Unmarshal(m, b)
}
func (m *InventoryReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InventoryReadResponse.Marshal(b, m, deterministic)
}
func (m *InventoryReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InventoryReadResponse.Merge(m, src)
}
func (m *InventoryReadResponse) XXX_Size() int {
	return xxx_messageInfo_InventoryReadResponse.Size(m)
}
func (m *InventoryReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InventoryReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InventoryReadResponse proto.InternalMessageInfo

func (m *InventoryReadResponse) GetInventory() *Inventory {
	if m != nil {
		return m.Inventory
	}
	return nil
}

type InventoryUpdateRequest struct {
	Charid               int64             `protobuf:"varint,1,opt,name=charid,proto3" json:"charid,omitempty"`
	Slotid               int64             `protobuf:"varint,2,opt,name=slotid,proto3" json:"slotid,omitempty"`
	Values               map[string]string `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *InventoryUpdateRequest) Reset()         { *m = InventoryUpdateRequest{} }
func (m *InventoryUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*InventoryUpdateRequest) ProtoMessage()    {}
func (*InventoryUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2d7d2d6cd9edf07, []int{6}
}

func (m *InventoryUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InventoryUpdateRequest.Unmarshal(m, b)
}
func (m *InventoryUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InventoryUpdateRequest.Marshal(b, m, deterministic)
}
func (m *InventoryUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InventoryUpdateRequest.Merge(m, src)
}
func (m *InventoryUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_InventoryUpdateRequest.Size(m)
}
func (m *InventoryUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InventoryUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InventoryUpdateRequest proto.InternalMessageInfo

func (m *InventoryUpdateRequest) GetCharid() int64 {
	if m != nil {
		return m.Charid
	}
	return 0
}

func (m *InventoryUpdateRequest) GetSlotid() int64 {
	if m != nil {
		return m.Slotid
	}
	return 0
}

func (m *InventoryUpdateRequest) GetValues() map[string]string {
	if m != nil {
		return m.Values
	}
	return nil
}

type InventoryUpdateResponse struct {
	Rowsaffected         int64    `protobuf:"varint,1,opt,name=rowsaffected,proto3" json:"rowsaffected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InventoryUpdateResponse) Reset()         { *m = InventoryUpdateResponse{} }
func (m *InventoryUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*InventoryUpdateResponse) ProtoMessage()    {}
func (*InventoryUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2d7d2d6cd9edf07, []int{7}
}

func (m *InventoryUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InventoryUpdateResponse.Unmarshal(m, b)
}
func (m *InventoryUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InventoryUpdateResponse.Marshal(b, m, deterministic)
}
func (m *InventoryUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InventoryUpdateResponse.Merge(m, src)
}
func (m *InventoryUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_InventoryUpdateResponse.Size(m)
}
func (m *InventoryUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InventoryUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InventoryUpdateResponse proto.InternalMessageInfo

func (m *InventoryUpdateResponse) GetRowsaffected() int64 {
	if m != nil {
		return m.Rowsaffected
	}
	return 0
}

type InventoryDeleteRequest struct {
	Charid               int64    `protobuf:"varint,1,opt,name=charid,proto3" json:"charid,omitempty"`
	Slotid               int64    `protobuf:"varint,2,opt,name=slotid,proto3" json:"slotid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InventoryDeleteRequest) Reset()         { *m = InventoryDeleteRequest{} }
func (m *InventoryDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*InventoryDeleteRequest) ProtoMessage()    {}
func (*InventoryDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2d7d2d6cd9edf07, []int{8}
}

func (m *InventoryDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InventoryDeleteRequest.Unmarshal(m, b)
}
func (m *InventoryDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InventoryDeleteRequest.Marshal(b, m, deterministic)
}
func (m *InventoryDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InventoryDeleteRequest.Merge(m, src)
}
func (m *InventoryDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_InventoryDeleteRequest.Size(m)
}
func (m *InventoryDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InventoryDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InventoryDeleteRequest proto.InternalMessageInfo

func (m *InventoryDeleteRequest) GetCharid() int64 {
	if m != nil {
		return m.Charid
	}
	return 0
}

func (m *InventoryDeleteRequest) GetSlotid() int64 {
	if m != nil {
		return m.Slotid
	}
	return 0
}

type InventoryDeleteResponse struct {
	Rowsaffected         int64    `protobuf:"varint,1,opt,name=rowsaffected,proto3" json:"rowsaffected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InventoryDeleteResponse) Reset()         { *m = InventoryDeleteResponse{} }
func (m *InventoryDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*InventoryDeleteResponse) ProtoMessage()    {}
func (*InventoryDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2d7d2d6cd9edf07, []int{9}
}

func (m *InventoryDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InventoryDeleteResponse.Unmarshal(m, b)
}
func (m *InventoryDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InventoryDeleteResponse.Marshal(b, m, deterministic)
}
func (m *InventoryDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InventoryDeleteResponse.Merge(m, src)
}
func (m *InventoryDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_InventoryDeleteResponse.Size(m)
}
func (m *InventoryDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InventoryDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InventoryDeleteResponse proto.InternalMessageInfo

func (m *InventoryDeleteResponse) GetRowsaffected() int64 {
	if m != nil {
		return m.Rowsaffected
	}
	return 0
}

type InventoryPatchRequest struct {
	Charid               int64    `protobuf:"varint,1,opt,name=charid,proto3" json:"charid,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Slotid               int64    `protobuf:"varint,4,opt,name=slotid,proto3" json:"slotid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InventoryPatchRequest) Reset()         { *m = InventoryPatchRequest{} }
func (m *InventoryPatchRequest) String() string { return proto.CompactTextString(m) }
func (*InventoryPatchRequest) ProtoMessage()    {}
func (*InventoryPatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2d7d2d6cd9edf07, []int{10}
}

func (m *InventoryPatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InventoryPatchRequest.Unmarshal(m, b)
}
func (m *InventoryPatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InventoryPatchRequest.Marshal(b, m, deterministic)
}
func (m *InventoryPatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InventoryPatchRequest.Merge(m, src)
}
func (m *InventoryPatchRequest) XXX_Size() int {
	return xxx_messageInfo_InventoryPatchRequest.Size(m)
}
func (m *InventoryPatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InventoryPatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InventoryPatchRequest proto.InternalMessageInfo

func (m *InventoryPatchRequest) GetCharid() int64 {
	if m != nil {
		return m.Charid
	}
	return 0
}

func (m *InventoryPatchRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *InventoryPatchRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *InventoryPatchRequest) GetSlotid() int64 {
	if m != nil {
		return m.Slotid
	}
	return 0
}

type InventoryPatchResponse struct {
	Rowsaffected         int64    `protobuf:"varint,1,opt,name=rowsaffected,proto3" json:"rowsaffected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InventoryPatchResponse) Reset()         { *m = InventoryPatchResponse{} }
func (m *InventoryPatchResponse) String() string { return proto.CompactTextString(m) }
func (*InventoryPatchResponse) ProtoMessage()    {}
func (*InventoryPatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2d7d2d6cd9edf07, []int{11}
}

func (m *InventoryPatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InventoryPatchResponse.Unmarshal(m, b)
}
func (m *InventoryPatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InventoryPatchResponse.Marshal(b, m, deterministic)
}
func (m *InventoryPatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InventoryPatchResponse.Merge(m, src)
}
func (m *InventoryPatchResponse) XXX_Size() int {
	return xxx_messageInfo_InventoryPatchResponse.Size(m)
}
func (m *InventoryPatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InventoryPatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InventoryPatchResponse proto.InternalMessageInfo

func (m *InventoryPatchResponse) GetRowsaffected() int64 {
	if m != nil {
		return m.Rowsaffected
	}
	return 0
}

func init() {
	proto.RegisterType((*InventorySearchRequest)(nil), "pb.InventorySearchRequest")
	proto.RegisterMapType((map[string]string)(nil), "pb.InventorySearchRequest.ValuesEntry")
	proto.RegisterType((*InventorySearchResponse)(nil), "pb.InventorySearchResponse")
	proto.RegisterType((*InventoryCreateRequest)(nil), "pb.InventoryCreateRequest")
	proto.RegisterMapType((map[string]string)(nil), "pb.InventoryCreateRequest.ValuesEntry")
	proto.RegisterType((*InventoryCreateResponse)(nil), "pb.InventoryCreateResponse")
	proto.RegisterType((*InventoryReadRequest)(nil), "pb.InventoryReadRequest")
	proto.RegisterType((*InventoryReadResponse)(nil), "pb.InventoryReadResponse")
	proto.RegisterType((*InventoryUpdateRequest)(nil), "pb.InventoryUpdateRequest")
	proto.RegisterMapType((map[string]string)(nil), "pb.InventoryUpdateRequest.ValuesEntry")
	proto.RegisterType((*InventoryUpdateResponse)(nil), "pb.InventoryUpdateResponse")
	proto.RegisterType((*InventoryDeleteRequest)(nil), "pb.InventoryDeleteRequest")
	proto.RegisterType((*InventoryDeleteResponse)(nil), "pb.InventoryDeleteResponse")
	proto.RegisterType((*InventoryPatchRequest)(nil), "pb.InventoryPatchRequest")
	proto.RegisterType((*InventoryPatchResponse)(nil), "pb.InventoryPatchResponse")
}

func init() {
	proto.RegisterFile("proto/inventory_service.proto", fileDescriptor_d2d7d2d6cd9edf07)
}

var fileDescriptor_d2d7d2d6cd9edf07 = []byte{
	// 626 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xcd, 0x6e, 0xd3, 0x4e,
	0x10, 0x97, 0xe3, 0x36, 0xff, 0x7f, 0xa6, 0x14, 0xaa, 0x55, 0x1b, 0x8c, 0x09, 0x22, 0x58, 0x08,
	0xa2, 0x20, 0x62, 0x11, 0x2e, 0x50, 0x01, 0x17, 0x0a, 0xa2, 0x37, 0x64, 0x04, 0x47, 0xd0, 0x26,
	0xde, 0x34, 0x16, 0xae, 0xd7, 0x78, 0xb7, 0x41, 0x51, 0xd5, 0x0b, 0xaf, 0xc0, 0x23, 0x21, 0x9e,
	0x80, 0x57, 0xe0, 0x25, 0xb8, 0xa1, 0xec, 0x47, 0xbd, 0xeb, 0xba, 0x6a, 0x5a, 0xe0, 0xe6, 0x99,
	0xdd, 0xcc, 0xef, 0x63, 0x76, 0x46, 0x81, 0x1b, 0x79, 0x41, 0x39, 0x0d, 0x93, 0x6c, 0x46, 0x32,
	0x4e, 0x8b, 0xf9, 0x07, 0x46, 0x8a, 0x59, 0x32, 0x26, 0x03, 0x91, 0x47, 0x8d, 0x7c, 0xe4, 0x77,
	0xf6, 0x28, 0xdd, 0x4b, 0x49, 0x88, 0xf3, 0x24, 0xc4, 0x59, 0x46, 0x39, 0xe6, 0x09, 0xcd, 0x98,
	0xbc, 0xe1, 0x6f, 0x55, 0x0a, 0xc8, 0x74, 0xf0, 0xcb, 0x81, 0xf6, 0xae, 0xce, 0xbd, 0x21, 0xb8,
	0x18, 0x4f, 0x23, 0xf2, 0xe9, 0x80, 0x30, 0x8e, 0x9e, 0x41, 0x73, 0x86, 0xd3, 0x03, 0xc2, 0x3c,
	0xa7, 0xeb, 0xf6, 0xd6, 0x86, 0x77, 0x06, 0xf9, 0x68, 0x50, 0x7f, 0x77, 0xf0, 0x4e, 0x5c, 0x7c,
	0x91, 0xf1, 0x62, 0x1e, 0xa9, 0x5f, 0xa1, 0x4d, 0x58, 0x4d, 0x93, 0xfd, 0x84, 0x7b, 0x8d, 0xae,
	0xd3, 0x73, 0x23, 0x19, 0xa0, 0x36, 0x34, 0xe9, 0x64, 0xc2, 0x08, 0xf7, 0x5c, 0x91, 0x56, 0x11,
	0xf2, 0xe0, 0x3f, 0x5a, 0xc4, 0xa4, 0x18, 0xcd, 0xbd, 0x95, 0xae, 0xd3, 0x6b, 0x45, 0x3a, 0x44,
	0x1d, 0x68, 0x89, 0xcf, 0x98, 0xb0, 0xb1, 0xb7, 0xda, 0x75, 0x7a, 0xff, 0x47, 0x65, 0xc2, 0x7f,
	0x0c, 0x6b, 0x06, 0x38, 0xda, 0x00, 0xf7, 0x23, 0x99, 0x7b, 0x8e, 0x28, 0xb1, 0xf8, 0x5c, 0xd0,
	0x10, 0x84, 0x04, 0x8d, 0x56, 0x24, 0x83, 0xed, 0xc6, 0x23, 0x27, 0x78, 0x0f, 0x57, 0x4f, 0xc8,
	0x61, 0x39, 0xcd, 0x18, 0x41, 0xf7, 0x01, 0x8e, 0x8f, 0xb4, 0xfe, 0x75, 0x4b, 0x7f, 0x64, 0x5c,
	0x58, 0x60, 0x70, 0xca, 0x71, 0xaa, 0xa5, 0x8a, 0x20, 0xf8, 0x66, 0x7a, 0xfb, 0xbc, 0x20, 0x98,
	0x13, 0xed, 0x6d, 0x1b, 0x9a, 0xe3, 0x29, 0x2e, 0x92, 0x58, 0x30, 0x75, 0x23, 0x15, 0x2d, 0xf2,
	0x2c, 0xa5, 0x3c, 0x89, 0x55, 0x25, 0x15, 0x19, 0xbd, 0x70, 0x6b, 0x7a, 0x61, 0xd5, 0xae, 0xeb,
	0xc5, 0x9f, 0xb8, 0xb4, 0x6b, 0xb8, 0xa4, 0x81, 0x94, 0x4b, 0xe7, 0x54, 0x11, 0xbc, 0x84, 0xcd,
	0xd2, 0x3f, 0x82, 0xe3, 0x0b, 0xba, 0x11, 0xec, 0xc0, 0x56, 0xa5, 0x8e, 0x22, 0x74, 0x0f, 0x5a,
	0xc7, 0x0f, 0x5c, 0xd4, 0x3a, 0xd1, 0xb5, 0xf2, 0xdc, 0x6e, 0xcf, 0xdb, 0x3c, 0xfe, 0x67, 0xed,
	0xb1, 0x6a, 0xff, 0xed, 0xf6, 0x3c, 0x35, 0xda, 0xa3, 0x81, 0x94, 0x1b, 0x01, 0x5c, 0x2a, 0xe8,
	0x67, 0x86, 0x27, 0x13, 0x32, 0xe6, 0x44, 0x6b, 0xb1, 0x72, 0xc1, 0x2b, 0xc3, 0x83, 0x1d, 0x92,
	0x92, 0x0b, 0x7b, 0x60, 0x11, 0xd1, 0x95, 0xce, 0x41, 0x84, 0x1a, 0x3d, 0x7d, 0x8d, 0x79, 0xb9,
	0x86, 0x4e, 0xe3, 0xa1, 0x4c, 0x6a, 0xd4, 0x98, 0xe4, 0x1a, 0x26, 0x19, 0x7c, 0x57, 0x2c, 0xbe,
	0x4f, 0x0c, 0xe5, 0x0a, 0x70, 0x79, 0xba, 0xc3, 0xef, 0xab, 0xb0, 0x61, 0x2c, 0x0f, 0xb1, 0x8b,
	0xd1, 0x14, 0xae, 0x54, 0x16, 0x0a, 0xf2, 0x4f, 0x5f, 0x9a, 0xfe, 0xf5, 0xda, 0x33, 0x49, 0x22,
	0xe8, 0x7c, 0xf9, 0xf1, 0xf3, 0x6b, 0xa3, 0x8d, 0x36, 0xc3, 0xd9, 0x83, 0x72, 0x6b, 0x87, 0x4c,
	0x96, 0x9d, 0x19, 0x48, 0x72, 0x28, 0x2b, 0x48, 0xd6, 0x4a, 0xa8, 0x20, 0xd9, 0x53, 0x1c, 0xf4,
	0x05, 0xd2, 0xed, 0xe0, 0xa6, 0x8d, 0x74, 0x28, 0x7d, 0x3e, 0x0a, 0x0f, 0xa5, 0x61, 0x47, 0xdb,
	0x4e, 0x1f, 0xed, 0xc3, 0xba, 0x35, 0x79, 0xc8, 0xb3, 0xc7, 0xab, 0x1c, 0x6a, 0xff, 0x5a, 0xcd,
	0x89, 0x42, 0xbc, 0x2b, 0x10, 0x6f, 0xa1, 0xb3, 0x10, 0x2d, 0x99, 0xf2, 0x71, 0x57, 0x64, 0x5a,
	0xa3, 0x55, 0x91, 0x69, 0x4f, 0x83, 0x96, 0xe9, 0x2f, 0x23, 0x93, 0x19, 0xb8, 0xf2, 0x2d, 0x57,
	0x70, 0xad, 0x51, 0xa9, 0xe0, 0xda, 0x8f, 0x5f, 0x8b, 0xed, 0x9f, 0x29, 0x96, 0xc1, 0x65, 0xfb,
	0x41, 0x22, 0xdb, 0x42, 0x73, 0x2a, 0x7c, 0xbf, 0xee, 0xc8, 0x56, 0x3a, 0x5c, 0x42, 0xe9, 0xa8,
	0x29, 0xfe, 0x06, 0x3c, 0xfc, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x2e, 0x1d, 0xf0, 0xbf, 0x60, 0x08,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// InventoryServiceClient is the client API for InventoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InventoryServiceClient interface {
	InventorySearch(ctx context.Context, in *InventorySearchRequest, opts ...grpc.CallOption) (*InventorySearchResponse, error)
	InventoryCreate(ctx context.Context, in *InventoryCreateRequest, opts ...grpc.CallOption) (*InventoryCreateResponse, error)
	InventoryRead(ctx context.Context, in *InventoryReadRequest, opts ...grpc.CallOption) (*InventoryReadResponse, error)
	InventoryUpdate(ctx context.Context, in *InventoryUpdateRequest, opts ...grpc.CallOption) (*InventoryUpdateResponse, error)
	InventoryDelete(ctx context.Context, in *InventoryDeleteRequest, opts ...grpc.CallOption) (*InventoryDeleteResponse, error)
	InventoryPatch(ctx context.Context, in *InventoryPatchRequest, opts ...grpc.CallOption) (*InventoryPatchResponse, error)
}

type inventoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryServiceClient(cc grpc.ClientConnInterface) InventoryServiceClient {
	return &inventoryServiceClient{cc}
}

func (c *inventoryServiceClient) InventorySearch(ctx context.Context, in *InventorySearchRequest, opts ...grpc.CallOption) (*InventorySearchResponse, error) {
	out := new(InventorySearchResponse)
	err := c.cc.Invoke(ctx, "/pb.InventoryService/InventorySearch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) InventoryCreate(ctx context.Context, in *InventoryCreateRequest, opts ...grpc.CallOption) (*InventoryCreateResponse, error) {
	out := new(InventoryCreateResponse)
	err := c.cc.Invoke(ctx, "/pb.InventoryService/InventoryCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) InventoryRead(ctx context.Context, in *InventoryReadRequest, opts ...grpc.CallOption) (*InventoryReadResponse, error) {
	out := new(InventoryReadResponse)
	err := c.cc.Invoke(ctx, "/pb.InventoryService/InventoryRead", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) InventoryUpdate(ctx context.Context, in *InventoryUpdateRequest, opts ...grpc.CallOption) (*InventoryUpdateResponse, error) {
	out := new(InventoryUpdateResponse)
	err := c.cc.Invoke(ctx, "/pb.InventoryService/InventoryUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) InventoryDelete(ctx context.Context, in *InventoryDeleteRequest, opts ...grpc.CallOption) (*InventoryDeleteResponse, error) {
	out := new(InventoryDeleteResponse)
	err := c.cc.Invoke(ctx, "/pb.InventoryService/InventoryDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) InventoryPatch(ctx context.Context, in *InventoryPatchRequest, opts ...grpc.CallOption) (*InventoryPatchResponse, error) {
	out := new(InventoryPatchResponse)
	err := c.cc.Invoke(ctx, "/pb.InventoryService/InventoryPatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryServiceServer is the server API for InventoryService service.
type InventoryServiceServer interface {
	InventorySearch(context.Context, *InventorySearchRequest) (*InventorySearchResponse, error)
	InventoryCreate(context.Context, *InventoryCreateRequest) (*InventoryCreateResponse, error)
	InventoryRead(context.Context, *InventoryReadRequest) (*InventoryReadResponse, error)
	InventoryUpdate(context.Context, *InventoryUpdateRequest) (*InventoryUpdateResponse, error)
	InventoryDelete(context.Context, *InventoryDeleteRequest) (*InventoryDeleteResponse, error)
	InventoryPatch(context.Context, *InventoryPatchRequest) (*InventoryPatchResponse, error)
}

// UnimplementedInventoryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedInventoryServiceServer struct {
}

func (*UnimplementedInventoryServiceServer) InventorySearch(ctx context.Context, req *InventorySearchRequest) (*InventorySearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InventorySearch not implemented")
}
func (*UnimplementedInventoryServiceServer) InventoryCreate(ctx context.Context, req *InventoryCreateRequest) (*InventoryCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InventoryCreate not implemented")
}
func (*UnimplementedInventoryServiceServer) InventoryRead(ctx context.Context, req *InventoryReadRequest) (*InventoryReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InventoryRead not implemented")
}
func (*UnimplementedInventoryServiceServer) InventoryUpdate(ctx context.Context, req *InventoryUpdateRequest) (*InventoryUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InventoryUpdate not implemented")
}
func (*UnimplementedInventoryServiceServer) InventoryDelete(ctx context.Context, req *InventoryDeleteRequest) (*InventoryDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InventoryDelete not implemented")
}
func (*UnimplementedInventoryServiceServer) InventoryPatch(ctx context.Context, req *InventoryPatchRequest) (*InventoryPatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InventoryPatch not implemented")
}

func RegisterInventoryServiceServer(s *grpc.Server, srv InventoryServiceServer) {
	s.RegisterService(&_InventoryService_serviceDesc, srv)
}

func _InventoryService_InventorySearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InventorySearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).InventorySearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.InventoryService/InventorySearch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).InventorySearch(ctx, req.(*InventorySearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_InventoryCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InventoryCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).InventoryCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.InventoryService/InventoryCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).InventoryCreate(ctx, req.(*InventoryCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_InventoryRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InventoryReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).InventoryRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.InventoryService/InventoryRead",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).InventoryRead(ctx, req.(*InventoryReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_InventoryUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InventoryUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).InventoryUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.InventoryService/InventoryUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).InventoryUpdate(ctx, req.(*InventoryUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_InventoryDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InventoryDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).InventoryDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.InventoryService/InventoryDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).InventoryDelete(ctx, req.(*InventoryDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_InventoryPatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InventoryPatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).InventoryPatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.InventoryService/InventoryPatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).InventoryPatch(ctx, req.(*InventoryPatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _InventoryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.InventoryService",
	HandlerType: (*InventoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InventorySearch",
			Handler:    _InventoryService_InventorySearch_Handler,
		},
		{
			MethodName: "InventoryCreate",
			Handler:    _InventoryService_InventoryCreate_Handler,
		},
		{
			MethodName: "InventoryRead",
			Handler:    _InventoryService_InventoryRead_Handler,
		},
		{
			MethodName: "InventoryUpdate",
			Handler:    _InventoryService_InventoryUpdate_Handler,
		},
		{
			MethodName: "InventoryDelete",
			Handler:    _InventoryService_InventoryDelete_Handler,
		},
		{
			MethodName: "InventoryPatch",
			Handler:    _InventoryService_InventoryPatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/inventory_service.proto",
}
