// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/login_account_service.proto

package pb

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginAccountSearchRequest struct {
	Values               map[string]string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Limit                int64             `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int64             `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Orderby              string            `protobuf:"bytes,4,opt,name=orderby,proto3" json:"orderby,omitempty"`
	Orderdesc            bool              `protobuf:"varint,5,opt,name=orderdesc,proto3" json:"orderdesc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *LoginAccountSearchRequest) Reset()         { *m = LoginAccountSearchRequest{} }
func (m *LoginAccountSearchRequest) String() string { return proto.CompactTextString(m) }
func (*LoginAccountSearchRequest) ProtoMessage()    {}
func (*LoginAccountSearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_996dd1676690bea1, []int{0}
}

func (m *LoginAccountSearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAccountSearchRequest.Unmarshal(m, b)
}
func (m *LoginAccountSearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAccountSearchRequest.Marshal(b, m, deterministic)
}
func (m *LoginAccountSearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAccountSearchRequest.Merge(m, src)
}
func (m *LoginAccountSearchRequest) XXX_Size() int {
	return xxx_messageInfo_LoginAccountSearchRequest.Size(m)
}
func (m *LoginAccountSearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAccountSearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAccountSearchRequest proto.InternalMessageInfo

func (m *LoginAccountSearchRequest) GetValues() map[string]string {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *LoginAccountSearchRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *LoginAccountSearchRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *LoginAccountSearchRequest) GetOrderby() string {
	if m != nil {
		return m.Orderby
	}
	return ""
}

func (m *LoginAccountSearchRequest) GetOrderdesc() bool {
	if m != nil {
		return m.Orderdesc
	}
	return false
}

type LoginAccountSearchResponse struct {
	LoginAccounts        []*LoginAccount `protobuf:"bytes,1,rep,name=LoginAccounts,proto3" json:"LoginAccounts,omitempty"`
	Total                int64           `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *LoginAccountSearchResponse) Reset()         { *m = LoginAccountSearchResponse{} }
func (m *LoginAccountSearchResponse) String() string { return proto.CompactTextString(m) }
func (*LoginAccountSearchResponse) ProtoMessage()    {}
func (*LoginAccountSearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_996dd1676690bea1, []int{1}
}

func (m *LoginAccountSearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAccountSearchResponse.Unmarshal(m, b)
}
func (m *LoginAccountSearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAccountSearchResponse.Marshal(b, m, deterministic)
}
func (m *LoginAccountSearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAccountSearchResponse.Merge(m, src)
}
func (m *LoginAccountSearchResponse) XXX_Size() int {
	return xxx_messageInfo_LoginAccountSearchResponse.Size(m)
}
func (m *LoginAccountSearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAccountSearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAccountSearchResponse proto.InternalMessageInfo

func (m *LoginAccountSearchResponse) GetLoginAccounts() []*LoginAccount {
	if m != nil {
		return m.LoginAccounts
	}
	return nil
}

func (m *LoginAccountSearchResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type LoginAccountCreateRequest struct {
	Values               map[string]string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *LoginAccountCreateRequest) Reset()         { *m = LoginAccountCreateRequest{} }
func (m *LoginAccountCreateRequest) String() string { return proto.CompactTextString(m) }
func (*LoginAccountCreateRequest) ProtoMessage()    {}
func (*LoginAccountCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_996dd1676690bea1, []int{2}
}

func (m *LoginAccountCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAccountCreateRequest.Unmarshal(m, b)
}
func (m *LoginAccountCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAccountCreateRequest.Marshal(b, m, deterministic)
}
func (m *LoginAccountCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAccountCreateRequest.Merge(m, src)
}
func (m *LoginAccountCreateRequest) XXX_Size() int {
	return xxx_messageInfo_LoginAccountCreateRequest.Size(m)
}
func (m *LoginAccountCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAccountCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAccountCreateRequest proto.InternalMessageInfo

func (m *LoginAccountCreateRequest) GetValues() map[string]string {
	if m != nil {
		return m.Values
	}
	return nil
}

type LoginAccountCreateResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginAccountCreateResponse) Reset()         { *m = LoginAccountCreateResponse{} }
func (m *LoginAccountCreateResponse) String() string { return proto.CompactTextString(m) }
func (*LoginAccountCreateResponse) ProtoMessage()    {}
func (*LoginAccountCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_996dd1676690bea1, []int{3}
}

func (m *LoginAccountCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAccountCreateResponse.Unmarshal(m, b)
}
func (m *LoginAccountCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAccountCreateResponse.Marshal(b, m, deterministic)
}
func (m *LoginAccountCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAccountCreateResponse.Merge(m, src)
}
func (m *LoginAccountCreateResponse) XXX_Size() int {
	return xxx_messageInfo_LoginAccountCreateResponse.Size(m)
}
func (m *LoginAccountCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAccountCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAccountCreateResponse proto.InternalMessageInfo

func (m *LoginAccountCreateResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type LoginAccountReadRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginAccountReadRequest) Reset()         { *m = LoginAccountReadRequest{} }
func (m *LoginAccountReadRequest) String() string { return proto.CompactTextString(m) }
func (*LoginAccountReadRequest) ProtoMessage()    {}
func (*LoginAccountReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_996dd1676690bea1, []int{4}
}

func (m *LoginAccountReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAccountReadRequest.Unmarshal(m, b)
}
func (m *LoginAccountReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAccountReadRequest.Marshal(b, m, deterministic)
}
func (m *LoginAccountReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAccountReadRequest.Merge(m, src)
}
func (m *LoginAccountReadRequest) XXX_Size() int {
	return xxx_messageInfo_LoginAccountReadRequest.Size(m)
}
func (m *LoginAccountReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAccountReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAccountReadRequest proto.InternalMessageInfo

func (m *LoginAccountReadRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type LoginAccountReadResponse struct {
	LoginAccount         *LoginAccount `protobuf:"bytes,1,opt,name=loginAccount,proto3" json:"loginAccount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *LoginAccountReadResponse) Reset()         { *m = LoginAccountReadResponse{} }
func (m *LoginAccountReadResponse) String() string { return proto.CompactTextString(m) }
func (*LoginAccountReadResponse) ProtoMessage()    {}
func (*LoginAccountReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_996dd1676690bea1, []int{5}
}

func (m *LoginAccountReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAccountReadResponse.Unmarshal(m, b)
}
func (m *LoginAccountReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAccountReadResponse.Marshal(b, m, deterministic)
}
func (m *LoginAccountReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAccountReadResponse.Merge(m, src)
}
func (m *LoginAccountReadResponse) XXX_Size() int {
	return xxx_messageInfo_LoginAccountReadResponse.Size(m)
}
func (m *LoginAccountReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAccountReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAccountReadResponse proto.InternalMessageInfo

func (m *LoginAccountReadResponse) GetLoginAccount() *LoginAccount {
	if m != nil {
		return m.LoginAccount
	}
	return nil
}

type LoginAccountUpdateRequest struct {
	Id                   int64             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Values               map[string]string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *LoginAccountUpdateRequest) Reset()         { *m = LoginAccountUpdateRequest{} }
func (m *LoginAccountUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*LoginAccountUpdateRequest) ProtoMessage()    {}
func (*LoginAccountUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_996dd1676690bea1, []int{6}
}

func (m *LoginAccountUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAccountUpdateRequest.Unmarshal(m, b)
}
func (m *LoginAccountUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAccountUpdateRequest.Marshal(b, m, deterministic)
}
func (m *LoginAccountUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAccountUpdateRequest.Merge(m, src)
}
func (m *LoginAccountUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_LoginAccountUpdateRequest.Size(m)
}
func (m *LoginAccountUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAccountUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAccountUpdateRequest proto.InternalMessageInfo

func (m *LoginAccountUpdateRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LoginAccountUpdateRequest) GetValues() map[string]string {
	if m != nil {
		return m.Values
	}
	return nil
}

type LoginAccountUpdateResponse struct {
	Rowsaffected         int64    `protobuf:"varint,1,opt,name=rowsaffected,proto3" json:"rowsaffected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginAccountUpdateResponse) Reset()         { *m = LoginAccountUpdateResponse{} }
func (m *LoginAccountUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*LoginAccountUpdateResponse) ProtoMessage()    {}
func (*LoginAccountUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_996dd1676690bea1, []int{7}
}

func (m *LoginAccountUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAccountUpdateResponse.Unmarshal(m, b)
}
func (m *LoginAccountUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAccountUpdateResponse.Marshal(b, m, deterministic)
}
func (m *LoginAccountUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAccountUpdateResponse.Merge(m, src)
}
func (m *LoginAccountUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_LoginAccountUpdateResponse.Size(m)
}
func (m *LoginAccountUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAccountUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAccountUpdateResponse proto.InternalMessageInfo

func (m *LoginAccountUpdateResponse) GetRowsaffected() int64 {
	if m != nil {
		return m.Rowsaffected
	}
	return 0
}

type LoginAccountDeleteRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginAccountDeleteRequest) Reset()         { *m = LoginAccountDeleteRequest{} }
func (m *LoginAccountDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*LoginAccountDeleteRequest) ProtoMessage()    {}
func (*LoginAccountDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_996dd1676690bea1, []int{8}
}

func (m *LoginAccountDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAccountDeleteRequest.Unmarshal(m, b)
}
func (m *LoginAccountDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAccountDeleteRequest.Marshal(b, m, deterministic)
}
func (m *LoginAccountDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAccountDeleteRequest.Merge(m, src)
}
func (m *LoginAccountDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_LoginAccountDeleteRequest.Size(m)
}
func (m *LoginAccountDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAccountDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAccountDeleteRequest proto.InternalMessageInfo

func (m *LoginAccountDeleteRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type LoginAccountDeleteResponse struct {
	Rowsaffected         int64    `protobuf:"varint,1,opt,name=rowsaffected,proto3" json:"rowsaffected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginAccountDeleteResponse) Reset()         { *m = LoginAccountDeleteResponse{} }
func (m *LoginAccountDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*LoginAccountDeleteResponse) ProtoMessage()    {}
func (*LoginAccountDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_996dd1676690bea1, []int{9}
}

func (m *LoginAccountDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAccountDeleteResponse.Unmarshal(m, b)
}
func (m *LoginAccountDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAccountDeleteResponse.Marshal(b, m, deterministic)
}
func (m *LoginAccountDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAccountDeleteResponse.Merge(m, src)
}
func (m *LoginAccountDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_LoginAccountDeleteResponse.Size(m)
}
func (m *LoginAccountDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAccountDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAccountDeleteResponse proto.InternalMessageInfo

func (m *LoginAccountDeleteResponse) GetRowsaffected() int64 {
	if m != nil {
		return m.Rowsaffected
	}
	return 0
}

type LoginAccountPatchRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginAccountPatchRequest) Reset()         { *m = LoginAccountPatchRequest{} }
func (m *LoginAccountPatchRequest) String() string { return proto.CompactTextString(m) }
func (*LoginAccountPatchRequest) ProtoMessage()    {}
func (*LoginAccountPatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_996dd1676690bea1, []int{10}
}

func (m *LoginAccountPatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAccountPatchRequest.Unmarshal(m, b)
}
func (m *LoginAccountPatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAccountPatchRequest.Marshal(b, m, deterministic)
}
func (m *LoginAccountPatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAccountPatchRequest.Merge(m, src)
}
func (m *LoginAccountPatchRequest) XXX_Size() int {
	return xxx_messageInfo_LoginAccountPatchRequest.Size(m)
}
func (m *LoginAccountPatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAccountPatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAccountPatchRequest proto.InternalMessageInfo

func (m *LoginAccountPatchRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LoginAccountPatchRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *LoginAccountPatchRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type LoginAccountPatchResponse struct {
	Rowsaffected         int64    `protobuf:"varint,1,opt,name=rowsaffected,proto3" json:"rowsaffected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginAccountPatchResponse) Reset()         { *m = LoginAccountPatchResponse{} }
func (m *LoginAccountPatchResponse) String() string { return proto.CompactTextString(m) }
func (*LoginAccountPatchResponse) ProtoMessage()    {}
func (*LoginAccountPatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_996dd1676690bea1, []int{11}
}

func (m *LoginAccountPatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAccountPatchResponse.Unmarshal(m, b)
}
func (m *LoginAccountPatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAccountPatchResponse.Marshal(b, m, deterministic)
}
func (m *LoginAccountPatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAccountPatchResponse.Merge(m, src)
}
func (m *LoginAccountPatchResponse) XXX_Size() int {
	return xxx_messageInfo_LoginAccountPatchResponse.Size(m)
}
func (m *LoginAccountPatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAccountPatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAccountPatchResponse proto.InternalMessageInfo

func (m *LoginAccountPatchResponse) GetRowsaffected() int64 {
	if m != nil {
		return m.Rowsaffected
	}
	return 0
}

func init() {
	proto.RegisterType((*LoginAccountSearchRequest)(nil), "pb.LoginAccountSearchRequest")
	proto.RegisterMapType((map[string]string)(nil), "pb.LoginAccountSearchRequest.ValuesEntry")
	proto.RegisterType((*LoginAccountSearchResponse)(nil), "pb.LoginAccountSearchResponse")
	proto.RegisterType((*LoginAccountCreateRequest)(nil), "pb.LoginAccountCreateRequest")
	proto.RegisterMapType((map[string]string)(nil), "pb.LoginAccountCreateRequest.ValuesEntry")
	proto.RegisterType((*LoginAccountCreateResponse)(nil), "pb.LoginAccountCreateResponse")
	proto.RegisterType((*LoginAccountReadRequest)(nil), "pb.LoginAccountReadRequest")
	proto.RegisterType((*LoginAccountReadResponse)(nil), "pb.LoginAccountReadResponse")
	proto.RegisterType((*LoginAccountUpdateRequest)(nil), "pb.LoginAccountUpdateRequest")
	proto.RegisterMapType((map[string]string)(nil), "pb.LoginAccountUpdateRequest.ValuesEntry")
	proto.RegisterType((*LoginAccountUpdateResponse)(nil), "pb.LoginAccountUpdateResponse")
	proto.RegisterType((*LoginAccountDeleteRequest)(nil), "pb.LoginAccountDeleteRequest")
	proto.RegisterType((*LoginAccountDeleteResponse)(nil), "pb.LoginAccountDeleteResponse")
	proto.RegisterType((*LoginAccountPatchRequest)(nil), "pb.LoginAccountPatchRequest")
	proto.RegisterType((*LoginAccountPatchResponse)(nil), "pb.LoginAccountPatchResponse")
}

func init() { proto.RegisterFile("proto/login_account_service.proto", fileDescriptor_996dd1676690bea1) }

var fileDescriptor_996dd1676690bea1 = []byte{
	// 616 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xcd, 0x8e, 0xd3, 0x30,
	0x10, 0x56, 0x12, 0x5a, 0xa8, 0x77, 0x41, 0xc5, 0xb0, 0x34, 0xcd, 0xb6, 0x50, 0x7c, 0xea, 0x2e,
	0xa8, 0x15, 0x05, 0x21, 0xd8, 0x0b, 0xac, 0x80, 0x1b, 0x87, 0x55, 0x10, 0x5c, 0x57, 0x6e, 0xe2,
	0x96, 0x40, 0x88, 0x43, 0xe2, 0x16, 0x55, 0x88, 0x0b, 0xaf, 0xc0, 0x89, 0x47, 0xe0, 0x55, 0xb8,
	0xf2, 0x0a, 0xbc, 0x07, 0x28, 0x76, 0xa2, 0x66, 0xe2, 0x84, 0x1f, 0xc1, 0x2d, 0xf6, 0x8c, 0xe7,
	0x9b, 0xef, 0xeb, 0x7c, 0x53, 0x74, 0x3d, 0x4e, 0xb8, 0xe0, 0xd3, 0x90, 0x2f, 0x83, 0xe8, 0x94,
	0x7a, 0x1e, 0x5f, 0x45, 0xe2, 0x34, 0x65, 0xc9, 0x3a, 0xf0, 0xd8, 0x44, 0xc6, 0xb0, 0x19, 0xcf,
	0x9d, 0xc1, 0x92, 0xf3, 0x65, 0xc8, 0xa6, 0x34, 0x0e, 0xa6, 0x34, 0x8a, 0xb8, 0xa0, 0x22, 0xe0,
	0x51, 0xaa, 0x32, 0x9c, 0x7e, 0x4d, 0x11, 0x15, 0x22, 0x3f, 0x0c, 0xd4, 0x7f, 0x9a, 0xdd, 0x1f,
	0xab, 0xeb, 0x67, 0x8c, 0x26, 0xde, 0x4b, 0x97, 0xbd, 0x5d, 0xb1, 0x54, 0xe0, 0x63, 0xd4, 0x5e,
	0xd3, 0x70, 0xc5, 0x52, 0xdb, 0x18, 0x59, 0xe3, 0x9d, 0xd9, 0xc1, 0x24, 0x9e, 0x4f, 0x1a, 0xd3,
	0x27, 0x2f, 0x64, 0xee, 0x93, 0x48, 0x24, 0x1b, 0x37, 0x7f, 0x88, 0x2f, 0xa3, 0x56, 0x18, 0xbc,
	0x09, 0x84, 0x6d, 0x8e, 0x8c, 0xb1, 0xe5, 0xaa, 0x03, 0xbe, 0x82, 0xda, 0x7c, 0xb1, 0x48, 0x99,
	0xb0, 0x2d, 0x79, 0x9d, 0x9f, 0xb0, 0x8d, 0xce, 0xf2, 0xc4, 0x67, 0xc9, 0x7c, 0x63, 0x9f, 0x19,
	0x19, 0xe3, 0x8e, 0x5b, 0x1c, 0xf1, 0x00, 0x75, 0xe4, 0xa7, 0xcf, 0x52, 0xcf, 0x6e, 0x8d, 0x8c,
	0xf1, 0x39, 0x77, 0x7b, 0xe1, 0xdc, 0x47, 0x3b, 0x25, 0x70, 0xdc, 0x45, 0xd6, 0x6b, 0xb6, 0xb1,
	0x0d, 0x59, 0x22, 0xfb, 0xcc, 0xda, 0x90, 0x0d, 0xc9, 0x36, 0x3a, 0xae, 0x3a, 0x1c, 0x99, 0xf7,
	0x0c, 0xf2, 0x0a, 0x39, 0x75, 0x8c, 0xd2, 0x98, 0x47, 0x29, 0xc3, 0x77, 0xd1, 0xf9, 0x72, 0xb4,
	0x10, 0xa2, 0x5b, 0x15, 0xc2, 0x85, 0x69, 0x19, 0x9e, 0xe0, 0x82, 0x86, 0x05, 0x6d, 0x79, 0x20,
	0x9f, 0x2b, 0x6a, 0x3f, 0x4a, 0x18, 0x15, 0x4c, 0x57, 0xdb, 0xac, 0x57, 0x1b, 0xa4, 0xd7, 0xa9,
	0xfd, 0x2f, 0x3a, 0xdc, 0x84, 0x3a, 0x14, 0x58, 0xb9, 0x0e, 0x17, 0x90, 0x19, 0xf8, 0xb2, 0x90,
	0xe5, 0x9a, 0x81, 0x4f, 0x0e, 0x50, 0x0f, 0xd0, 0x67, 0xd4, 0x2f, 0x68, 0x54, 0x53, 0x4f, 0x90,
	0xad, 0xa7, 0xe6, 0x65, 0xef, 0xa0, 0xdd, 0xb0, 0x14, 0x93, 0xaf, 0xea, 0xd4, 0x05, 0x59, 0xe4,
	0x4b, 0x45, 0xc6, 0xe7, 0xb1, 0x5f, 0x92, 0xb1, 0x82, 0xff, 0x7b, 0x59, 0xc1, 0xf3, 0xff, 0x2d,
	0xeb, 0x43, 0x28, 0x6b, 0x81, 0x95, 0xf3, 0x27, 0x68, 0x37, 0xe1, 0xef, 0x52, 0xba, 0x58, 0x30,
	0x4f, 0xb0, 0xa2, 0x6b, 0x70, 0x47, 0x6e, 0x40, 0xb2, 0x8f, 0x59, 0xc8, 0x1a, 0xc9, 0x56, 0xe1,
	0x8a, 0xe4, 0xbf, 0x80, 0x73, 0xe1, 0xcf, 0x75, 0x42, 0xc5, 0x76, 0x1f, 0x54, 0xa5, 0xcd, 0x85,
	0x30, 0x6b, 0x84, 0xb0, 0x4a, 0x42, 0x90, 0x07, 0x90, 0x42, 0x5e, 0xf3, 0xcf, 0x9b, 0x9a, 0x7d,
	0x6d, 0xa1, 0x4b, 0xd0, 0xa5, 0x72, 0x03, 0x62, 0x81, 0xb0, 0x6e, 0x5e, 0x3c, 0xfc, 0xe5, 0x9a,
	0x72, 0xae, 0x36, 0x85, 0x55, 0x43, 0xe4, 0xda, 0xc7, 0x6f, 0xdf, 0x3f, 0x99, 0x7d, 0xdc, 0x9b,
	0xae, 0x6f, 0xa9, 0xa5, 0x99, 0xef, 0xcc, 0x69, 0xaa, 0xea, 0xc7, 0x10, 0x55, 0x59, 0x45, 0x47,
	0x05, 0x76, 0xd5, 0x51, 0xa1, 0xc3, 0xc8, 0xbe, 0x44, 0xdd, 0x23, 0xdd, 0x2a, 0xea, 0x91, 0x71,
	0x88, 0x43, 0xd4, 0xad, 0x7a, 0x08, 0xef, 0x6b, 0x2e, 0xd9, 0x9a, 0xd0, 0x19, 0xd4, 0x07, 0x73,
	0xac, 0xa1, 0xc4, 0xea, 0xe1, 0x3d, 0x8d, 0xe1, 0xfb, 0xc0, 0xff, 0x80, 0x57, 0x90, 0x9f, 0x9a,
	0x59, 0x9d, 0x1f, 0xf0, 0x8d, 0xce, 0x0f, 0x8e, 0x3a, 0x19, 0x49, 0x4c, 0xc7, 0xa9, 0xc7, 0xcc,
	0x48, 0x26, 0x10, 0x56, 0xcd, 0xae, 0x0e, 0x0b, 0x0c, 0xa0, 0xc3, 0xc2, 0x91, 0x2f, 0xa8, 0x1e,
	0x36, 0x50, 0x4d, 0xd0, 0x45, 0x6d, 0x32, 0xb1, 0x26, 0x5e, 0xd9, 0x04, 0xce, 0xb0, 0x21, 0x0a,
	0x79, 0xce, 0x1a, 0x79, 0xce, 0xdb, 0xf2, 0xaf, 0xf7, 0xf6, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x79, 0x1e, 0xb1, 0x89, 0xdc, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// LoginAccountServiceClient is the client API for LoginAccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LoginAccountServiceClient interface {
	LoginAccountSearch(ctx context.Context, in *LoginAccountSearchRequest, opts ...grpc.CallOption) (*LoginAccountSearchResponse, error)
	LoginAccountCreate(ctx context.Context, in *LoginAccountCreateRequest, opts ...grpc.CallOption) (*LoginAccountCreateResponse, error)
	LoginAccountRead(ctx context.Context, in *LoginAccountReadRequest, opts ...grpc.CallOption) (*LoginAccountReadResponse, error)
	LoginAccountUpdate(ctx context.Context, in *LoginAccountUpdateRequest, opts ...grpc.CallOption) (*LoginAccountUpdateResponse, error)
	LoginAccountDelete(ctx context.Context, in *LoginAccountDeleteRequest, opts ...grpc.CallOption) (*LoginAccountDeleteResponse, error)
	LoginAccountPatch(ctx context.Context, in *LoginAccountPatchRequest, opts ...grpc.CallOption) (*LoginAccountPatchResponse, error)
}

type loginAccountServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLoginAccountServiceClient(cc grpc.ClientConnInterface) LoginAccountServiceClient {
	return &loginAccountServiceClient{cc}
}

func (c *loginAccountServiceClient) LoginAccountSearch(ctx context.Context, in *LoginAccountSearchRequest, opts ...grpc.CallOption) (*LoginAccountSearchResponse, error) {
	out := new(LoginAccountSearchResponse)
	err := c.cc.Invoke(ctx, "/pb.LoginAccountService/LoginAccountSearch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginAccountServiceClient) LoginAccountCreate(ctx context.Context, in *LoginAccountCreateRequest, opts ...grpc.CallOption) (*LoginAccountCreateResponse, error) {
	out := new(LoginAccountCreateResponse)
	err := c.cc.Invoke(ctx, "/pb.LoginAccountService/LoginAccountCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginAccountServiceClient) LoginAccountRead(ctx context.Context, in *LoginAccountReadRequest, opts ...grpc.CallOption) (*LoginAccountReadResponse, error) {
	out := new(LoginAccountReadResponse)
	err := c.cc.Invoke(ctx, "/pb.LoginAccountService/LoginAccountRead", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginAccountServiceClient) LoginAccountUpdate(ctx context.Context, in *LoginAccountUpdateRequest, opts ...grpc.CallOption) (*LoginAccountUpdateResponse, error) {
	out := new(LoginAccountUpdateResponse)
	err := c.cc.Invoke(ctx, "/pb.LoginAccountService/LoginAccountUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginAccountServiceClient) LoginAccountDelete(ctx context.Context, in *LoginAccountDeleteRequest, opts ...grpc.CallOption) (*LoginAccountDeleteResponse, error) {
	out := new(LoginAccountDeleteResponse)
	err := c.cc.Invoke(ctx, "/pb.LoginAccountService/LoginAccountDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginAccountServiceClient) LoginAccountPatch(ctx context.Context, in *LoginAccountPatchRequest, opts ...grpc.CallOption) (*LoginAccountPatchResponse, error) {
	out := new(LoginAccountPatchResponse)
	err := c.cc.Invoke(ctx, "/pb.LoginAccountService/LoginAccountPatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoginAccountServiceServer is the server API for LoginAccountService service.
type LoginAccountServiceServer interface {
	LoginAccountSearch(context.Context, *LoginAccountSearchRequest) (*LoginAccountSearchResponse, error)
	LoginAccountCreate(context.Context, *LoginAccountCreateRequest) (*LoginAccountCreateResponse, error)
	LoginAccountRead(context.Context, *LoginAccountReadRequest) (*LoginAccountReadResponse, error)
	LoginAccountUpdate(context.Context, *LoginAccountUpdateRequest) (*LoginAccountUpdateResponse, error)
	LoginAccountDelete(context.Context, *LoginAccountDeleteRequest) (*LoginAccountDeleteResponse, error)
	LoginAccountPatch(context.Context, *LoginAccountPatchRequest) (*LoginAccountPatchResponse, error)
}

// UnimplementedLoginAccountServiceServer can be embedded to have forward compatible implementations.
type UnimplementedLoginAccountServiceServer struct {
}

func (*UnimplementedLoginAccountServiceServer) LoginAccountSearch(ctx context.Context, req *LoginAccountSearchRequest) (*LoginAccountSearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginAccountSearch not implemented")
}
func (*UnimplementedLoginAccountServiceServer) LoginAccountCreate(ctx context.Context, req *LoginAccountCreateRequest) (*LoginAccountCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginAccountCreate not implemented")
}
func (*UnimplementedLoginAccountServiceServer) LoginAccountRead(ctx context.Context, req *LoginAccountReadRequest) (*LoginAccountReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginAccountRead not implemented")
}
func (*UnimplementedLoginAccountServiceServer) LoginAccountUpdate(ctx context.Context, req *LoginAccountUpdateRequest) (*LoginAccountUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginAccountUpdate not implemented")
}
func (*UnimplementedLoginAccountServiceServer) LoginAccountDelete(ctx context.Context, req *LoginAccountDeleteRequest) (*LoginAccountDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginAccountDelete not implemented")
}
func (*UnimplementedLoginAccountServiceServer) LoginAccountPatch(ctx context.Context, req *LoginAccountPatchRequest) (*LoginAccountPatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginAccountPatch not implemented")
}

func RegisterLoginAccountServiceServer(s *grpc.Server, srv LoginAccountServiceServer) {
	s.RegisterService(&_LoginAccountService_serviceDesc, srv)
}

func _LoginAccountService_LoginAccountSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginAccountSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginAccountServiceServer).LoginAccountSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LoginAccountService/LoginAccountSearch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginAccountServiceServer).LoginAccountSearch(ctx, req.(*LoginAccountSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoginAccountService_LoginAccountCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginAccountCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginAccountServiceServer).LoginAccountCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LoginAccountService/LoginAccountCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginAccountServiceServer).LoginAccountCreate(ctx, req.(*LoginAccountCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoginAccountService_LoginAccountRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginAccountReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginAccountServiceServer).LoginAccountRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LoginAccountService/LoginAccountRead",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginAccountServiceServer).LoginAccountRead(ctx, req.(*LoginAccountReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoginAccountService_LoginAccountUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginAccountUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginAccountServiceServer).LoginAccountUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LoginAccountService/LoginAccountUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginAccountServiceServer).LoginAccountUpdate(ctx, req.(*LoginAccountUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoginAccountService_LoginAccountDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginAccountDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginAccountServiceServer).LoginAccountDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LoginAccountService/LoginAccountDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginAccountServiceServer).LoginAccountDelete(ctx, req.(*LoginAccountDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoginAccountService_LoginAccountPatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginAccountPatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginAccountServiceServer).LoginAccountPatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LoginAccountService/LoginAccountPatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginAccountServiceServer).LoginAccountPatch(ctx, req.(*LoginAccountPatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LoginAccountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.LoginAccountService",
	HandlerType: (*LoginAccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginAccountSearch",
			Handler:    _LoginAccountService_LoginAccountSearch_Handler,
		},
		{
			MethodName: "LoginAccountCreate",
			Handler:    _LoginAccountService_LoginAccountCreate_Handler,
		},
		{
			MethodName: "LoginAccountRead",
			Handler:    _LoginAccountService_LoginAccountRead_Handler,
		},
		{
			MethodName: "LoginAccountUpdate",
			Handler:    _LoginAccountService_LoginAccountUpdate_Handler,
		},
		{
			MethodName: "LoginAccountDelete",
			Handler:    _LoginAccountService_LoginAccountDelete_Handler,
		},
		{
			MethodName: "LoginAccountPatch",
			Handler:    _LoginAccountService_LoginAccountPatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/login_account_service.proto",
}
