// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/zone_service.proto

package pb

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ZoneSearchRequest struct {
	Values               map[string]string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Limit                int64             `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int64             `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Orderby              string            `protobuf:"bytes,4,opt,name=orderby,proto3" json:"orderby,omitempty"`
	Orderdesc            bool              `protobuf:"varint,5,opt,name=orderdesc,proto3" json:"orderdesc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ZoneSearchRequest) Reset()         { *m = ZoneSearchRequest{} }
func (m *ZoneSearchRequest) String() string { return proto.CompactTextString(m) }
func (*ZoneSearchRequest) ProtoMessage()    {}
func (*ZoneSearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a2d2fdbcf763886, []int{0}
}

func (m *ZoneSearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZoneSearchRequest.Unmarshal(m, b)
}
func (m *ZoneSearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZoneSearchRequest.Marshal(b, m, deterministic)
}
func (m *ZoneSearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZoneSearchRequest.Merge(m, src)
}
func (m *ZoneSearchRequest) XXX_Size() int {
	return xxx_messageInfo_ZoneSearchRequest.Size(m)
}
func (m *ZoneSearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ZoneSearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ZoneSearchRequest proto.InternalMessageInfo

func (m *ZoneSearchRequest) GetValues() map[string]string {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *ZoneSearchRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ZoneSearchRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ZoneSearchRequest) GetOrderby() string {
	if m != nil {
		return m.Orderby
	}
	return ""
}

func (m *ZoneSearchRequest) GetOrderdesc() bool {
	if m != nil {
		return m.Orderdesc
	}
	return false
}

type ZoneSearchResponse struct {
	Zones                []*Zone  `protobuf:"bytes,1,rep,name=Zones,proto3" json:"Zones,omitempty"`
	Total                int64    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZoneSearchResponse) Reset()         { *m = ZoneSearchResponse{} }
func (m *ZoneSearchResponse) String() string { return proto.CompactTextString(m) }
func (*ZoneSearchResponse) ProtoMessage()    {}
func (*ZoneSearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a2d2fdbcf763886, []int{1}
}

func (m *ZoneSearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZoneSearchResponse.Unmarshal(m, b)
}
func (m *ZoneSearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZoneSearchResponse.Marshal(b, m, deterministic)
}
func (m *ZoneSearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZoneSearchResponse.Merge(m, src)
}
func (m *ZoneSearchResponse) XXX_Size() int {
	return xxx_messageInfo_ZoneSearchResponse.Size(m)
}
func (m *ZoneSearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ZoneSearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ZoneSearchResponse proto.InternalMessageInfo

func (m *ZoneSearchResponse) GetZones() []*Zone {
	if m != nil {
		return m.Zones
	}
	return nil
}

func (m *ZoneSearchResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type ZoneCreateRequest struct {
	Values               map[string]string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ZoneCreateRequest) Reset()         { *m = ZoneCreateRequest{} }
func (m *ZoneCreateRequest) String() string { return proto.CompactTextString(m) }
func (*ZoneCreateRequest) ProtoMessage()    {}
func (*ZoneCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a2d2fdbcf763886, []int{2}
}

func (m *ZoneCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZoneCreateRequest.Unmarshal(m, b)
}
func (m *ZoneCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZoneCreateRequest.Marshal(b, m, deterministic)
}
func (m *ZoneCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZoneCreateRequest.Merge(m, src)
}
func (m *ZoneCreateRequest) XXX_Size() int {
	return xxx_messageInfo_ZoneCreateRequest.Size(m)
}
func (m *ZoneCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ZoneCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ZoneCreateRequest proto.InternalMessageInfo

func (m *ZoneCreateRequest) GetValues() map[string]string {
	if m != nil {
		return m.Values
	}
	return nil
}

type ZoneCreateResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZoneCreateResponse) Reset()         { *m = ZoneCreateResponse{} }
func (m *ZoneCreateResponse) String() string { return proto.CompactTextString(m) }
func (*ZoneCreateResponse) ProtoMessage()    {}
func (*ZoneCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a2d2fdbcf763886, []int{3}
}

func (m *ZoneCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZoneCreateResponse.Unmarshal(m, b)
}
func (m *ZoneCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZoneCreateResponse.Marshal(b, m, deterministic)
}
func (m *ZoneCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZoneCreateResponse.Merge(m, src)
}
func (m *ZoneCreateResponse) XXX_Size() int {
	return xxx_messageInfo_ZoneCreateResponse.Size(m)
}
func (m *ZoneCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ZoneCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ZoneCreateResponse proto.InternalMessageInfo

func (m *ZoneCreateResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ZoneReadRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZoneReadRequest) Reset()         { *m = ZoneReadRequest{} }
func (m *ZoneReadRequest) String() string { return proto.CompactTextString(m) }
func (*ZoneReadRequest) ProtoMessage()    {}
func (*ZoneReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a2d2fdbcf763886, []int{4}
}

func (m *ZoneReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZoneReadRequest.Unmarshal(m, b)
}
func (m *ZoneReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZoneReadRequest.Marshal(b, m, deterministic)
}
func (m *ZoneReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZoneReadRequest.Merge(m, src)
}
func (m *ZoneReadRequest) XXX_Size() int {
	return xxx_messageInfo_ZoneReadRequest.Size(m)
}
func (m *ZoneReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ZoneReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ZoneReadRequest proto.InternalMessageInfo

func (m *ZoneReadRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ZoneReadResponse struct {
	Zone                 *Zone    `protobuf:"bytes,1,opt,name=zone,proto3" json:"zone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZoneReadResponse) Reset()         { *m = ZoneReadResponse{} }
func (m *ZoneReadResponse) String() string { return proto.CompactTextString(m) }
func (*ZoneReadResponse) ProtoMessage()    {}
func (*ZoneReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a2d2fdbcf763886, []int{5}
}

func (m *ZoneReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZoneReadResponse.Unmarshal(m, b)
}
func (m *ZoneReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZoneReadResponse.Marshal(b, m, deterministic)
}
func (m *ZoneReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZoneReadResponse.Merge(m, src)
}
func (m *ZoneReadResponse) XXX_Size() int {
	return xxx_messageInfo_ZoneReadResponse.Size(m)
}
func (m *ZoneReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ZoneReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ZoneReadResponse proto.InternalMessageInfo

func (m *ZoneReadResponse) GetZone() *Zone {
	if m != nil {
		return m.Zone
	}
	return nil
}

type ZoneUpdateRequest struct {
	Id                   int64             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Values               map[string]string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ZoneUpdateRequest) Reset()         { *m = ZoneUpdateRequest{} }
func (m *ZoneUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*ZoneUpdateRequest) ProtoMessage()    {}
func (*ZoneUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a2d2fdbcf763886, []int{6}
}

func (m *ZoneUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZoneUpdateRequest.Unmarshal(m, b)
}
func (m *ZoneUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZoneUpdateRequest.Marshal(b, m, deterministic)
}
func (m *ZoneUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZoneUpdateRequest.Merge(m, src)
}
func (m *ZoneUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_ZoneUpdateRequest.Size(m)
}
func (m *ZoneUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ZoneUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ZoneUpdateRequest proto.InternalMessageInfo

func (m *ZoneUpdateRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ZoneUpdateRequest) GetValues() map[string]string {
	if m != nil {
		return m.Values
	}
	return nil
}

type ZoneUpdateResponse struct {
	Rowsaffected         int64    `protobuf:"varint,1,opt,name=rowsaffected,proto3" json:"rowsaffected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZoneUpdateResponse) Reset()         { *m = ZoneUpdateResponse{} }
func (m *ZoneUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*ZoneUpdateResponse) ProtoMessage()    {}
func (*ZoneUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a2d2fdbcf763886, []int{7}
}

func (m *ZoneUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZoneUpdateResponse.Unmarshal(m, b)
}
func (m *ZoneUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZoneUpdateResponse.Marshal(b, m, deterministic)
}
func (m *ZoneUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZoneUpdateResponse.Merge(m, src)
}
func (m *ZoneUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_ZoneUpdateResponse.Size(m)
}
func (m *ZoneUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ZoneUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ZoneUpdateResponse proto.InternalMessageInfo

func (m *ZoneUpdateResponse) GetRowsaffected() int64 {
	if m != nil {
		return m.Rowsaffected
	}
	return 0
}

type ZoneDeleteRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZoneDeleteRequest) Reset()         { *m = ZoneDeleteRequest{} }
func (m *ZoneDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*ZoneDeleteRequest) ProtoMessage()    {}
func (*ZoneDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a2d2fdbcf763886, []int{8}
}

func (m *ZoneDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZoneDeleteRequest.Unmarshal(m, b)
}
func (m *ZoneDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZoneDeleteRequest.Marshal(b, m, deterministic)
}
func (m *ZoneDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZoneDeleteRequest.Merge(m, src)
}
func (m *ZoneDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_ZoneDeleteRequest.Size(m)
}
func (m *ZoneDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ZoneDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ZoneDeleteRequest proto.InternalMessageInfo

func (m *ZoneDeleteRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ZoneDeleteResponse struct {
	Rowsaffected         int64    `protobuf:"varint,1,opt,name=rowsaffected,proto3" json:"rowsaffected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZoneDeleteResponse) Reset()         { *m = ZoneDeleteResponse{} }
func (m *ZoneDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*ZoneDeleteResponse) ProtoMessage()    {}
func (*ZoneDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a2d2fdbcf763886, []int{9}
}

func (m *ZoneDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZoneDeleteResponse.Unmarshal(m, b)
}
func (m *ZoneDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZoneDeleteResponse.Marshal(b, m, deterministic)
}
func (m *ZoneDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZoneDeleteResponse.Merge(m, src)
}
func (m *ZoneDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_ZoneDeleteResponse.Size(m)
}
func (m *ZoneDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ZoneDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ZoneDeleteResponse proto.InternalMessageInfo

func (m *ZoneDeleteResponse) GetRowsaffected() int64 {
	if m != nil {
		return m.Rowsaffected
	}
	return 0
}

type ZonePatchRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZonePatchRequest) Reset()         { *m = ZonePatchRequest{} }
func (m *ZonePatchRequest) String() string { return proto.CompactTextString(m) }
func (*ZonePatchRequest) ProtoMessage()    {}
func (*ZonePatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a2d2fdbcf763886, []int{10}
}

func (m *ZonePatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZonePatchRequest.Unmarshal(m, b)
}
func (m *ZonePatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZonePatchRequest.Marshal(b, m, deterministic)
}
func (m *ZonePatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZonePatchRequest.Merge(m, src)
}
func (m *ZonePatchRequest) XXX_Size() int {
	return xxx_messageInfo_ZonePatchRequest.Size(m)
}
func (m *ZonePatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ZonePatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ZonePatchRequest proto.InternalMessageInfo

func (m *ZonePatchRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ZonePatchRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ZonePatchRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ZonePatchResponse struct {
	Rowsaffected         int64    `protobuf:"varint,1,opt,name=rowsaffected,proto3" json:"rowsaffected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZonePatchResponse) Reset()         { *m = ZonePatchResponse{} }
func (m *ZonePatchResponse) String() string { return proto.CompactTextString(m) }
func (*ZonePatchResponse) ProtoMessage()    {}
func (*ZonePatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a2d2fdbcf763886, []int{11}
}

func (m *ZonePatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZonePatchResponse.Unmarshal(m, b)
}
func (m *ZonePatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZonePatchResponse.Marshal(b, m, deterministic)
}
func (m *ZonePatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZonePatchResponse.Merge(m, src)
}
func (m *ZonePatchResponse) XXX_Size() int {
	return xxx_messageInfo_ZonePatchResponse.Size(m)
}
func (m *ZonePatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ZonePatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ZonePatchResponse proto.InternalMessageInfo

func (m *ZonePatchResponse) GetRowsaffected() int64 {
	if m != nil {
		return m.Rowsaffected
	}
	return 0
}

func init() {
	proto.RegisterType((*ZoneSearchRequest)(nil), "pb.ZoneSearchRequest")
	proto.RegisterMapType((map[string]string)(nil), "pb.ZoneSearchRequest.ValuesEntry")
	proto.RegisterType((*ZoneSearchResponse)(nil), "pb.ZoneSearchResponse")
	proto.RegisterType((*ZoneCreateRequest)(nil), "pb.ZoneCreateRequest")
	proto.RegisterMapType((map[string]string)(nil), "pb.ZoneCreateRequest.ValuesEntry")
	proto.RegisterType((*ZoneCreateResponse)(nil), "pb.ZoneCreateResponse")
	proto.RegisterType((*ZoneReadRequest)(nil), "pb.ZoneReadRequest")
	proto.RegisterType((*ZoneReadResponse)(nil), "pb.ZoneReadResponse")
	proto.RegisterType((*ZoneUpdateRequest)(nil), "pb.ZoneUpdateRequest")
	proto.RegisterMapType((map[string]string)(nil), "pb.ZoneUpdateRequest.ValuesEntry")
	proto.RegisterType((*ZoneUpdateResponse)(nil), "pb.ZoneUpdateResponse")
	proto.RegisterType((*ZoneDeleteRequest)(nil), "pb.ZoneDeleteRequest")
	proto.RegisterType((*ZoneDeleteResponse)(nil), "pb.ZoneDeleteResponse")
	proto.RegisterType((*ZonePatchRequest)(nil), "pb.ZonePatchRequest")
	proto.RegisterType((*ZonePatchResponse)(nil), "pb.ZonePatchResponse")
}

func init() {
	proto.RegisterFile("proto/zone_service.proto", fileDescriptor_3a2d2fdbcf763886)
}

var fileDescriptor_3a2d2fdbcf763886 = []byte{
	// 594 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x41, 0x6f, 0xd3, 0x4c,
	0x14, 0x94, 0xed, 0x24, 0x5f, 0xf2, 0xf2, 0x95, 0xa4, 0xdb, 0xa6, 0x58, 0x56, 0x84, 0xd2, 0x85,
	0x43, 0xd4, 0x43, 0x02, 0xe1, 0x40, 0xdb, 0x2b, 0x70, 0xa9, 0x38, 0x54, 0x86, 0x72, 0xe0, 0x82,
	0x9c, 0xf8, 0xa5, 0x58, 0x04, 0xaf, 0xb1, 0xb7, 0x41, 0x01, 0x71, 0xe9, 0x8d, 0x33, 0x27, 0x7e,
	0x17, 0x7f, 0x81, 0x3b, 0x7f, 0x01, 0x79, 0xd7, 0x9b, 0xf5, 0x3a, 0xa9, 0x04, 0x82, 0x9b, 0x77,
	0xf4, 0x3c, 0x3b, 0x33, 0x99, 0xe7, 0x80, 0x9b, 0xa4, 0x8c, 0xb3, 0xf1, 0x47, 0x16, 0xe3, 0xeb,
	0x0c, 0xd3, 0x65, 0x34, 0xc3, 0x91, 0x80, 0x88, 0x9d, 0x4c, 0xbd, 0xfe, 0x25, 0x63, 0x97, 0x0b,
	0x1c, 0x07, 0x49, 0x34, 0x0e, 0xe2, 0x98, 0xf1, 0x80, 0x47, 0x2c, 0xce, 0xe4, 0x84, 0xd7, 0xd5,
	0xef, 0x4a, 0x84, 0xfe, 0xb4, 0x60, 0xf7, 0x15, 0x8b, 0xf1, 0x39, 0x06, 0xe9, 0xec, 0x8d, 0x8f,
	0xef, 0xaf, 0x30, 0xe3, 0xe4, 0x04, 0x1a, 0xcb, 0x60, 0x71, 0x85, 0x99, 0x6b, 0x0d, 0x9c, 0x61,
	0x7b, 0x72, 0x38, 0x4a, 0xa6, 0xa3, 0x8d, 0xb1, 0xd1, 0x4b, 0x31, 0xf3, 0x34, 0xe6, 0xe9, 0xca,
	0x2f, 0x5e, 0x20, 0xfb, 0x50, 0x5f, 0x44, 0xef, 0x22, 0xee, 0xda, 0x03, 0x6b, 0xe8, 0xf8, 0xf2,
	0x40, 0x0e, 0xa0, 0xc1, 0xe6, 0xf3, 0x0c, 0xb9, 0xeb, 0x08, 0xb8, 0x38, 0x11, 0x17, 0xfe, 0x63,
	0x69, 0x88, 0xe9, 0x74, 0xe5, 0xd6, 0x06, 0xd6, 0xb0, 0xe5, 0xab, 0x23, 0xe9, 0x43, 0x4b, 0x3c,
	0x86, 0x98, 0xcd, 0xdc, 0xfa, 0xc0, 0x1a, 0x36, 0x7d, 0x0d, 0x78, 0x27, 0xd0, 0x2e, 0x5d, 0x4e,
	0xba, 0xe0, 0xbc, 0xc5, 0x95, 0x6b, 0x09, 0x8a, 0xfc, 0x31, 0x97, 0x21, 0x04, 0x09, 0x19, 0x2d,
	0x5f, 0x1e, 0x4e, 0xed, 0x63, 0x8b, 0x9e, 0x01, 0x29, 0x3b, 0xc9, 0x12, 0x16, 0x67, 0x48, 0xee,
	0x40, 0x3d, 0x47, 0x95, 0xe1, 0xa6, 0x32, 0xec, 0x4b, 0x38, 0xe7, 0xe3, 0x8c, 0x07, 0x0b, 0x65,
	0x4b, 0x1c, 0xe8, 0x97, 0x22, 0xbd, 0xc7, 0x29, 0x06, 0x1c, 0x37, 0xd3, 0xb3, 0xcd, 0xf4, 0x8c,
	0xb1, 0x6d, 0xe9, 0xfd, 0x8d, 0xaf, 0x7b, 0xd2, 0x97, 0xba, 0xa3, 0xf0, 0x75, 0x0b, 0xec, 0x28,
	0x14, 0x04, 0x8e, 0x6f, 0x47, 0x21, 0x3d, 0x84, 0x8e, 0xb0, 0x85, 0x41, 0xa8, 0xe4, 0x56, 0x47,
	0xee, 0x43, 0x57, 0x8f, 0x14, 0x34, 0x7d, 0xa8, 0xe5, 0xa5, 0x11, 0x53, 0xe5, 0x74, 0x04, 0x4a,
	0xbf, 0x15, 0x31, 0x5c, 0x24, 0x61, 0x29, 0x86, 0x0a, 0xef, 0xcd, 0xb1, 0x18, 0xaf, 0xfd, 0xeb,
	0x58, 0x8e, 0x65, 0x2c, 0xea, 0x8e, 0xc2, 0x0f, 0x85, 0xff, 0x53, 0xf6, 0x21, 0x0b, 0xe6, 0x73,
	0x9c, 0x71, 0x54, 0x2a, 0x0d, 0x8c, 0xde, 0x95, 0xa6, 0x9e, 0xe0, 0x02, 0x6f, 0x34, 0xa5, 0xe8,
	0xd5, 0xd0, 0x1f, 0xd0, 0x9f, 0xc9, 0x98, 0xcf, 0x03, 0xae, 0xf7, 0xae, 0x1a, 0x59, 0x61, 0xd4,
	0xde, 0x62, 0xd4, 0x29, 0x19, 0xa5, 0x8f, 0xa4, 0xd4, 0x82, 0xeb, 0xf7, 0x45, 0x4c, 0xae, 0x6b,
	0xd0, 0x96, 0xdb, 0x20, 0x3e, 0x24, 0xe4, 0x05, 0x80, 0x5e, 0x0e, 0xd2, 0xdb, 0xba, 0xf6, 0xde,
	0x41, 0x15, 0x96, 0x17, 0xd2, 0xdb, 0xd7, 0xdf, 0x7f, 0x7c, 0xb5, 0x77, 0x49, 0x67, 0xbc, 0x7c,
	0x20, 0xbe, 0x31, 0xe3, 0x4c, 0xf2, 0x9c, 0x4b, 0x56, 0x59, 0x4d, 0xcd, 0x6a, 0xac, 0x83, 0x66,
	0x35, 0x1b, 0x4c, 0xf7, 0x04, 0xeb, 0x0e, 0x6d, 0x2a, 0xd6, 0x53, 0xeb, 0x88, 0x3c, 0x83, 0xa6,
	0xea, 0x28, 0xd9, 0x5b, 0xb7, 0x51, 0x97, 0xda, 0xdb, 0x37, 0xc1, 0x82, 0xab, 0x27, 0xb8, 0x3a,
	0x64, 0x67, 0xad, 0xf0, 0x53, 0x14, 0x7e, 0x26, 0x17, 0x52, 0x9f, 0xec, 0x88, 0xd6, 0x67, 0xf4,
	0x52, 0xeb, 0x33, 0xab, 0x44, 0x5d, 0xc1, 0x49, 0x3c, 0x93, 0x33, 0x17, 0xe9, 0x4b, 0x5a, 0xd9,
	0x0d, 0x4d, 0x6b, 0x14, 0x4a, 0xd3, 0x9a, 0x15, 0x52, 0x52, 0x8f, 0x2a, 0x52, 0x7d, 0x68, 0xad,
	0x7f, 0x69, 0xb2, 0x36, 0x59, 0x2e, 0x91, 0xd7, 0xab, 0xa0, 0xa6, 0xce, 0xc9, 0x86, 0xce, 0x69,
	0x43, 0xfc, 0x15, 0x3c, 0xfc, 0x15, 0x00, 0x00, 0xff, 0xff, 0x96, 0x1a, 0x43, 0x0f, 0x5a, 0x06,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ZoneServiceClient is the client API for ZoneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ZoneServiceClient interface {
	ZoneSearch(ctx context.Context, in *ZoneSearchRequest, opts ...grpc.CallOption) (*ZoneSearchResponse, error)
	ZoneCreate(ctx context.Context, in *ZoneCreateRequest, opts ...grpc.CallOption) (*ZoneCreateResponse, error)
	ZoneRead(ctx context.Context, in *ZoneReadRequest, opts ...grpc.CallOption) (*ZoneReadResponse, error)
	ZoneUpdate(ctx context.Context, in *ZoneUpdateRequest, opts ...grpc.CallOption) (*ZoneUpdateResponse, error)
	ZoneDelete(ctx context.Context, in *ZoneDeleteRequest, opts ...grpc.CallOption) (*ZoneDeleteResponse, error)
	ZonePatch(ctx context.Context, in *ZonePatchRequest, opts ...grpc.CallOption) (*ZonePatchResponse, error)
}

type zoneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewZoneServiceClient(cc grpc.ClientConnInterface) ZoneServiceClient {
	return &zoneServiceClient{cc}
}

func (c *zoneServiceClient) ZoneSearch(ctx context.Context, in *ZoneSearchRequest, opts ...grpc.CallOption) (*ZoneSearchResponse, error) {
	out := new(ZoneSearchResponse)
	err := c.cc.Invoke(ctx, "/pb.ZoneService/ZoneSearch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneServiceClient) ZoneCreate(ctx context.Context, in *ZoneCreateRequest, opts ...grpc.CallOption) (*ZoneCreateResponse, error) {
	out := new(ZoneCreateResponse)
	err := c.cc.Invoke(ctx, "/pb.ZoneService/ZoneCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneServiceClient) ZoneRead(ctx context.Context, in *ZoneReadRequest, opts ...grpc.CallOption) (*ZoneReadResponse, error) {
	out := new(ZoneReadResponse)
	err := c.cc.Invoke(ctx, "/pb.ZoneService/ZoneRead", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneServiceClient) ZoneUpdate(ctx context.Context, in *ZoneUpdateRequest, opts ...grpc.CallOption) (*ZoneUpdateResponse, error) {
	out := new(ZoneUpdateResponse)
	err := c.cc.Invoke(ctx, "/pb.ZoneService/ZoneUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneServiceClient) ZoneDelete(ctx context.Context, in *ZoneDeleteRequest, opts ...grpc.CallOption) (*ZoneDeleteResponse, error) {
	out := new(ZoneDeleteResponse)
	err := c.cc.Invoke(ctx, "/pb.ZoneService/ZoneDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneServiceClient) ZonePatch(ctx context.Context, in *ZonePatchRequest, opts ...grpc.CallOption) (*ZonePatchResponse, error) {
	out := new(ZonePatchResponse)
	err := c.cc.Invoke(ctx, "/pb.ZoneService/ZonePatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZoneServiceServer is the server API for ZoneService service.
type ZoneServiceServer interface {
	ZoneSearch(context.Context, *ZoneSearchRequest) (*ZoneSearchResponse, error)
	ZoneCreate(context.Context, *ZoneCreateRequest) (*ZoneCreateResponse, error)
	ZoneRead(context.Context, *ZoneReadRequest) (*ZoneReadResponse, error)
	ZoneUpdate(context.Context, *ZoneUpdateRequest) (*ZoneUpdateResponse, error)
	ZoneDelete(context.Context, *ZoneDeleteRequest) (*ZoneDeleteResponse, error)
	ZonePatch(context.Context, *ZonePatchRequest) (*ZonePatchResponse, error)
}

// UnimplementedZoneServiceServer can be embedded to have forward compatible implementations.
type UnimplementedZoneServiceServer struct {
}

func (*UnimplementedZoneServiceServer) ZoneSearch(ctx context.Context, req *ZoneSearchRequest) (*ZoneSearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ZoneSearch not implemented")
}
func (*UnimplementedZoneServiceServer) ZoneCreate(ctx context.Context, req *ZoneCreateRequest) (*ZoneCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ZoneCreate not implemented")
}
func (*UnimplementedZoneServiceServer) ZoneRead(ctx context.Context, req *ZoneReadRequest) (*ZoneReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ZoneRead not implemented")
}
func (*UnimplementedZoneServiceServer) ZoneUpdate(ctx context.Context, req *ZoneUpdateRequest) (*ZoneUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ZoneUpdate not implemented")
}
func (*UnimplementedZoneServiceServer) ZoneDelete(ctx context.Context, req *ZoneDeleteRequest) (*ZoneDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ZoneDelete not implemented")
}
func (*UnimplementedZoneServiceServer) ZonePatch(ctx context.Context, req *ZonePatchRequest) (*ZonePatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ZonePatch not implemented")
}

func RegisterZoneServiceServer(s *grpc.Server, srv ZoneServiceServer) {
	s.RegisterService(&_ZoneService_serviceDesc, srv)
}

func _ZoneService_ZoneSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZoneSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).ZoneSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ZoneService/ZoneSearch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).ZoneSearch(ctx, req.(*ZoneSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZoneService_ZoneCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZoneCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).ZoneCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ZoneService/ZoneCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).ZoneCreate(ctx, req.(*ZoneCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZoneService_ZoneRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZoneReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).ZoneRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ZoneService/ZoneRead",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).ZoneRead(ctx, req.(*ZoneReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZoneService_ZoneUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZoneUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).ZoneUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ZoneService/ZoneUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).ZoneUpdate(ctx, req.(*ZoneUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZoneService_ZoneDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZoneDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).ZoneDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ZoneService/ZoneDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).ZoneDelete(ctx, req.(*ZoneDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZoneService_ZonePatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZonePatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).ZonePatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ZoneService/ZonePatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).ZonePatch(ctx, req.(*ZonePatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ZoneService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ZoneService",
	HandlerType: (*ZoneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ZoneSearch",
			Handler:    _ZoneService_ZoneSearch_Handler,
		},
		{
			MethodName: "ZoneCreate",
			Handler:    _ZoneService_ZoneCreate_Handler,
		},
		{
			MethodName: "ZoneRead",
			Handler:    _ZoneService_ZoneRead_Handler,
		},
		{
			MethodName: "ZoneUpdate",
			Handler:    _ZoneService_ZoneUpdate_Handler,
		},
		{
			MethodName: "ZoneDelete",
			Handler:    _ZoneService_ZoneDelete_Handler,
		},
		{
			MethodName: "ZonePatch",
			Handler:    _ZoneService_ZonePatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/zone_service.proto",
}
